### ISSUE TITLE
Always disabled

### ISSUE THREAD

**Issue by Bobpt** [madskristensen/BundlerMinifier#101]
Every time i start up visual studio 2015 this extension is always disabled.

Can anyone help me solve this problem?
Thanks

**Comment by madskristensen** [comment]
This is an issue with Visual Studio that happens to all extensions including Microsoft's own ones. Try this https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd
