### ISSUE TITLE
Globbing doesn't work on files excluded from project

### ISSUE THREAD

**Issue by kspeakman** [madskristensen/BundlerMinifier#102]
I have some .js files generated by TypeScript compiler in VS2015. The compiled .js files are not included in the project.

When I list them explicitly in the bundleconfig.json, they are compiled and minified (not in order though -- separate issue?). However, when I change to the globbing format (`App/**/*.js`), only the single .js file which is included in the project is put in the output file.

**Comment by kspeakman** [comment]
Ok, it only appears to do this when I build with "Enable bundle on build...". If I right-click the bundle.config and do Update bundles, it pulls everything in properly.

**Comment by madskristensen** [comment]
@kspeakman Did you update the `BuildBundlerMinifier` NuGet package to the latest version in your project?

**Comment by kspeakman** [comment]
Ah, no I didn't. I had just installed the extension and just enabled the bundle on build. I'll try that when I get back to work tomorrow.

**Comment by kspeakman** [comment]
I checked, and there are currently no updates available for BuildBundlerMinifier.

![image](https://cloud.githubusercontent.com/assets/4582668/13056203/7d3acad4-d3d9-11e5-9d93-b6535ea6c077.png)

The behavior on build is still: the .js bundle only processes (.js) files which are part of the solution. The build also fails if the output file is not already checked out. However, right-clicking `bundleconfig.json` and clicking `Update bundles` correctly processes all .js files given in the globbing pattern. Config is this:

```javascript
[
  {
    "outputFileName": "App/app.all.js",
    "inputFiles": [
      "App/**/*.js"
    ]
  }
]
```

**Comment by jbaan** [comment]
I have exactly same issue described above. Also upgraded to latest version but still skipping this files during build.

**Comment by jbaan** [comment]
I dived little more in this issue. It seems that during build also typescript compiler is removing the old js file a and copy new js files generated from the ts file. In the build targets of typescript this is done in the build target GetCopyToOutputDirectoryItemsDependsOn. So when I change the BuildBundlerMinifier.targets to this event as well, then typescript compiler and bundler will work together.

<PropertyGroup>
        <GetCopyToOutputDirectoryItemsDependsOn>
            BundleMinify;
            $(GetCopyToOutputDirectoryItemsDependsOn)
        </GetCopyToOutputDirectoryItemsDependsOn>
    </PropertyGroup>

**Comment by madskristensen** [comment]
Fixed in latest CI build
