### ISSUE TITLE
Do not update identical files

### ISSUE THREAD

**Issue by IlBaffo** [madskristensen/BundlerMinifier#103]
Hi, could be possible to not update minified files when the result would be identical?

When the `bundleconfig.json` file is updated, adding a new file or just saving it manually, every minified/bundled file gets checked out in the source control and this generates a mess the the pending changes because many files are really not changed.

Additionally, when the **Prompt for checkout** option is enabled in the `Source control > Enviroment > Editing` panel, trying to minify a new file generates an error because `bundleconfig.json` cannot be checked out silently and a manual checkout must be performed.

![add new minified file](https://cloud.githubusercontent.com/assets/7044910/12885090/62a4cf74-ce63-11e5-99c2-fbe3396f0e98.png)

Maybe our workflow is not compatible with this scenario and we have tried making multiple `bundleconfig.json` files in various folders but it gets trickier to keep track of them, do you have any suggestion? 

PS:
This applies to WebCompiler extension too

**Comment by madskristensen** [comment]
The extension checks if the content has changed before writing to the file system. If the content hasn't changed, nothing gets written and no check out happens. Are you using the latest version of this extension?

**Comment by IlBaffo** [comment]
Yep, updated today. It is behaving like this since the first release after the split.

**Comment by IlBaffo** [comment]
Wrong button!

**Comment by Code-DJ** [comment]
Hi I fixed this as part of #106 and submitted a pull request which was accepted by Mads today.
