### ISSUE TITLE
Visual Studio Clean failure when outputFileName is checked into revision control

### ISSUE THREAD

**Issue by bobwright** [madskristensen/BundlerMinifier#104]
We are getting a "The "BundlerMinifier.BundlerCleanTask" task failed unexpectedly" error in Visual Studio when a solution/project is being cleaned, which makes sense because the all of our outputFileName's are being checked into TFS and they are locked in our dev environments.  I took all of the outputFileNames in the project out of revision control thinking the Team Build would re-emit them and place them in the drop location however our Team Build definitions doesn't rebuild the outputFileName so it doesn't bundle these files during the build process. 

Is there a way to successfully clean a solution with the outputFileNames being checked into TFS revision control?
Or
Is there a way to get a TFS Team Build to Bundle, Minify and copy the outputFileNames to their proper locations? 
Or
Is there some other thing I can do to solve our problem?

**Comment by sneed424** [comment]
Also experiencing this issue. Any solution for this scenario?
