### ISSUE TITLE
Bundle & minify at build time only?

### ISSUE THREAD

**Issue by Marc22** [madskristensen/BundlerMinifier#107]
Is there a configuration to only generate minified bundles at build time?  Specifically for a particular configuration (e.g., release vs. debug).  Generally, we don't need minified files while developing, and don't want to slow things down for it.  But we certainly want to minify when building for release.

Also - at build time, all minified files are being rebuilt, even if no js files have been updated.  Is this expected?

thank you,
-Marc

**Comment by Code-DJ** [comment]
Hi, I fixed the "all files are being minified" as part of #106 and submitted a pull request which was merged by Mads today.
