### ISSUE TITLE
Encoding of non-latin characters during minification.

### ISSUE THREAD

**Issue by lalibi** [madskristensen/BundlerMinifier#109]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.8.148

### Description
Greek characters (or any non-latin ones I imagine) in a .js file get encoded on minification, although it doesn't seem necessary. The file uses utf-8.

### Steps to recreate
Include that in a .js file:
> var dayNamesShort = ['Κυρ', 'Δευ', 'Τρι', 'Τετ', 'Πεμ', 'Παρ', 'Σαβ'];

### Current behavior
It will produce:
> var dayNamesShort=["\u039a\u03c5\u03c1","\u0394\u03b5\u03c5","\u03a4\u03c1\u03b9","\u03a4\u03b5\u03c4","\u03a0\u03b5\u03bc","\u03a0\u03b1\u03c1","\u03a3\u03b1\u03b2"];

### Expected behavior
The code continues to work, but I don't see any benefits from encoding those values. The file size increases a bit, too.

**Comment by madskristensen** [comment]
Fixed
