### ISSUE TITLE
Bundle not generated when using the Web Compiler ext and BundlerMinifier

### ISSUE THREAD

**Issue by AndySarosy** [madskristensen/BundlerMinifier#114]
### Installed product versions
- Visual Studio: 2015 Professional, update 2
- This extension: 1.8.148
- Web Compiler" 1.10.306

### Description
If I make a change to one of my SCSS files, the compiler generates the CSS file as expected, but the bundler/minifier does not fire.  If I manually edit the CSS file, the bundler/minifier does fire and produces the output file as expected.  

### Steps to recreate
1. Edit SCSS file; CSS gets generated; Bundler/Minifier does not re-create bundle
2. Edit the CSS file generated in step 1; Bundler/Minifier does re-create bundle

### Current behavior
The CSS file that gets generated by the Web Compiler when changing a SCSS file isn't seen as a change by the Bundler/Minifier

### Expected behavior
The Bundler/Minifier should detect the change in the CSS file and recreate the bundle.

**Comment by Bokkeman** [comment]
Will be fixed if #105 is implemented

**Comment by AndySarosy** [comment]
Can you suggest a work around in the mean time?

**Comment by Bokkeman** [comment]
Sorry, I'm not a contributor to the project - I just noticed that the issues are related. I'm another affected and disgruntled user. 
My workflow is to force a Save on the generated CSS file (open, Ctrl-S) so that the bundler kicks off its task, but it is tedious and error-prone.

**Comment by madskristensen** [comment]
Please help verify this fix in the latest [CI build](http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/).

**Comment by madskristensen** [comment]
Please help verify this fix in the latest [CI build](http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/).

**Comment by madskristensen** [comment]
Can someone please help verify the CI build so I can release a new version?
