### ISSUE TITLE
Bundle on build doesn't add bundled file to project

### ISSUE THREAD

**Issue by qixotic-software** [madskristensen/BundlerMinifier#116]
### Installed product versions
- Visual Studio:2015 Enterprise
- This extension: 1.8.148

### Description
When the BundlerMinifier is set to bundle on build, it creates the .js and .min.js, but doesn't add them to the project.  This is causing false errors in the <script> tag where it's used

### Steps to recreate
1. Create a bundleconfig.json file, either manually or with the select / context menu method
2. Enable bundle on build...
3. build
4. show all files and refresh

### Current behavior
.js and .min.js files are created, not nested and not included in project.  This causes suggestions to be shown where the bundled files are referenced

### Expected behavior
bundle files should be included in project and nested.  Refresh shouldn't be necessary to see them

**Comment by madskristensen** [comment]
That's correct. MSBuild doesn't do that and that is by design. You should add the output files to your project first
