### ISSUE TITLE
for(let x of y.prop) being incorrectly replaced with for(let t of t.prop)

### ISSUE THREAD

**Issue by rexxmagnus** [madskristensen/BundlerMinifier#117]
### Installed product versions
- Visual Studio: 2015 community 14.0.25123.00 Update 2
- This extension: 1.8.148

### Description
Variables in for (x of y.property) loop are being replaced with for(let t of t.prop) and causing problems when t gets overwritten.

### Steps to recreate
Minify the following snippet:

function successCallback(response) {
    if (response.data) {
        for (let thing of response.data) {
            if (!someArray.find(function (item) { return item.prop == thing.prop; })) {
                someArray.push(thing);
            }
        }
    }
}

### Current behavior
Minifies to:
function successCallback(n){if(n.data)for(let n of n.data)someArray.find(function(t){return t.prop==n.prop})||someArray.push(n)}

let n of n.data is incorrect. The "let n" should be replaced by another letter, as n effectively overwrites the variable being referred to by "response" in the original code, breaking the reference.

If the for loop contains a direct reference to response.data (as opposed to the reference inside the anonymous inner function) the code gets minified correctly.

### Expected behavior
Adding in references to the looped objects (console.logged) gives correct output:

function successCallback(response) {
    if (response.data) {
        for (let thing of response.data) {
            console.log(thing);
            console.log(response.data);
            if (!someArray.find(function (item) { return item.prop == thing.prop; })) {
                someArray.push(thing);
            }
        }
    }
}

function successCallback(n){if(n.data)for(let t of n.data)console.log(t),console.log(n.data),someArray.find(function(n){return n.prop==t.prop})||someArray.push(t)}

**Comment by rexxmagnus** [comment]
I should note that this doesn't happen if using var in place of let.

**Comment by madskristensen** [comment]
Please open this bug on the [NUglify repo](https://github.com/xoofx/NUglify)
