### ISSUE TITLE
Javascript generated by TypeScript outputs does not trigger bundle regeneration

### ISSUE THREAD

**Issue by NinjaCross** [madskristensen/BundlerMinifier#118]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.8.148

### Description
TypeScript outputs are not correctly handled.
After saving a TypeScript file, the corresponding JS output is generated, but this operation on the JS file seems to be not monitored (even if the JS file is explicitly added to the bundling configuration), and so the bundle is not regenerated.

### Steps to recreate
1. Create a TS file
2. Save it. A JS file is generated/overwritten
3. Add the JS to the bundle configuration
4. Modify and save again the TS. The corresponding JS is regenerated.

### Current behavior
After step (4) the bundle is not updated

### Expected behavior
Afer step (4) the bundle should be updated

**Comment by madskristensen** [comment]
Can you please try the latest [CI build](http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/) where this issue should have been fixed?

**Comment by NinjaCross** [comment]
I will ASAP

**Comment by NinjaCross** [comment]
The fix worked perfectly, thanks
