### ISSUE TITLE
Automatically disabled after close and open VS 2015

### ISSUE THREAD

**Issue by tiagotomasel** [madskristensen/BundlerMinifier#121]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.9.155

### Description
Extension is automatically disabled after close visual studio

### Steps to recreate
1. Install the extension (if not installed the version 1.9.155)
2. Close visual studio
3. Open visual studio
4. The extension will be disabled
5. Enable the extension and repeat 2 to 4 and aways will be disabled

### Current behavior
Aways the extension is disabled after close and open visual studio

### Expected behavior
After close and open visual studio, the extension must remain enabled.

**Comment by madskristensen** [comment]
Unfortunately, this is not something caused by this extension but it's a bug in Visual Studio and how it caches extensibility items. Please try this https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd

**Comment by tiagotomasel** [comment]
Not solved, but i'll wait for a VS update. Thank you.

**Comment by mttmccb** [comment]
Still not solved in Update 3, it's really annoying as I wonder why my css updates aren't happening and it's always because of this...
