### ISSUE TITLE
Bundle not executed on save

### ISSUE THREAD

**Issue by ssougnez** [madskristensen/BundlerMinifier#123]
Hi,

since I updated Visual Studio 2015 to "Update 2", my bundle does not execute anymore when I save JavaScript file, I need to manually "Update bundle" every time I make changes which make this extension pretty useless.

Regards

**Comment by suddenelfilio** [comment]
Having the same issue here.

**Comment by alecrt** [comment]
Same here

**Comment by ssougnez** [comment]
Hi,

I just took a look at the source code and it appears that it comes from the fact that Visual Studio is not always handling file changes the same way. I created a new project where I tried to reproduce the issue I have with my bigger project but the extension worked fine. 

Then I decided to debug the extension with my bigger project and I noticed that when I change a file, Visual Studio:

- Create a temp file with the new content
- Delete the original file
- Rename the temp file

To support this behavior, I modified the file "_ProjectEventCommand_" by replacing the "_try ... catch_" block with this one:

```
try
{
    if (!string.IsNullOrEmpty(config) && File.Exists(config))
    {
        var fsw = new FileSystemWatcher(project.GetRootFolder());

        fsw.Changed += FileChanged;
        fsw.Created += FileChanged;
        fsw.Deleted += FileChanged;
        fsw.Renamed += FileChanged;

        fsw.IncludeSubdirectories = true;
        fsw.NotifyFilter = NotifyFilters.Size | NotifyFilters.CreationTime | NotifyFilters.FileName;
        fsw.EnableRaisingEvents = true;

        _listeners.TryAdd(project, fsw);
    }
}
catch (Exception ex)
{
    Logger.Log(ex);
}
```

Besides listening to the "_FileChanged_" event, I also listen to "_Created_", "_Deleted_" and "_Renamed_". I worked a bit with "FileSystemWatchers" before and "FileChanged" is not reliable enough, especially when messing with Visual Studio files. 

I also modified the "_NotifyFilters_" to catch the "_FileName_" changes, otherwise, it would not work. I tested this solution and it works. Moreover, the tests defined in the test project are all green after this modification.

I hope that you'll merge this solution (or an another) with the current code, but during that time, I'll use the modified extension :-)

Thanks

**Comment by madskristensen** [comment]
Awesome. Would it be enough to just change the NotifyFilter?

**Comment by ssougnez** [comment]
Nop. However, if you ask that for the performances, I just did the test and you are not forced to listen to "_Deleted_" and "_Created_". In my case, listenning to "_Renamed_" is enough but, of course, I cannot ensure that it covers all situations ;-)

**Comment by madskristensen** [comment]
The fix is in the latest [CI build](http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/). Please help verify it works before I push to the VS Gallery. 

Thanks for the help on this

**Comment by ssougnez** [comment]
Just tried it and it works as expected.

Thanks
