### ISSUE TITLE
Ability to have conditional comments in html for minification

### ISSUE THREAD

**Issue by CheloXL** [madskristensen/BundlerMinifier#125]
This is a suggestion/question and not a but per se. I would like to be able to have something similar to the #if DEBUG //#else //#endif in my html code, that of course would need to work with some kind of conditional comments.

In that way, I can reference my non bundled, non minified files when running in debug mode, and have references to the .min css/js files.

Please note that the "running in debug mode" here is just a preference and it is not related at all with the running environment.

Example:
```
<!--[if MINIMIZE]>
	<script src="js/bundle.min.js"></script>
<![endif]-->
<![if !MINIMIZE]>
	<script src="js/library1.js"></script>
	<script src="js/library2.js"></script>
	<script src="js/application.js"></script>
<![endif]>
```

So, when fetching the non-minified page, the browser will execute what's inside the !MINIMIZE section, and when minimized, that section is removed and the code inside the MINIMIZE section is promoted from the comment.

**Comment by madskristensen** [comment]
Please open this bug on the [NUglify repo](https://github.com/xoofx/NUglify)
