### ISSUE TITLE
JavaScript bundles not updated when script changes if stored outside of root drive

### ISSUE THREAD

**Issue by shawnlehner** [madskristensen/BundlerMinifier#126]
### Installed product versions
- Visual Studio 2015 Community
- This extension: 1.9.155

### Description
When project files are saved on a drive that is not your root drive (for example Windows is on C:\ and your project files are on D:\) then script bundles are not updated when one of the included scripts is modified and saved.

### Steps to recreate
1. Place project files on a non-OS drive (D:\ in my case)
2. Change a script file
3. Bundle output will not be updated.

### Current behavior
I am running into an issue with JavaScript bundle generation via the Bundler & Minifier extension. I saw a similar issue report for the 2013 version, so I am not sure if this is related.

I have two machines, both running Visual Studio 2015 Community with the same Extensions. I have the exact same project code on both machines. Machine a) has the project source on the C:\ drive (Windows drive) while b) has the project source on a the D:\ drive (Not Windows).

Machine a) works perfect. Each time I save a JS file I see a "Compiled successfully" and then a "Bundle updated" message in the status bar. When observing the output bundle, it has my saved changes.

Machine b) does not work so perfectly. When saving I see the "Compiled succesfully" message but I never see the "Bundle updated" message. When I observe the output bundle it has not been updated.

I can "Enable bundle on build" on machine b) and it will correctly build the bundles when I make a new build of the project. Unfortunately, this is pretty annoying because then I have to wait for all the new binaries to load to refresh and test my JavaScript.

### Expected behavior
The script bundles on Machine b) would update when a script file is changed.

**Comment by madskristensen** [comment]
This should have been fixed in the newly released 1.9.157. Can you please verify?

**Comment by moojjoo** [comment]
mads, love your work, however the ability to update the primary file example global.css or global.js is not updating the global.min.css or global.min.js files any longer this was an awesome feature.  Any reason why this would not work.  I have 1.9.157 installed.

**Comment by madskristensen** [comment]
Can you please try the very latest [CI build](http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/) and see if the issue still exist?

**Comment by madskristensen** [comment]
Any update on this?

**Comment by madskristensen** [comment]
@moojjoo and @shawnlehner, did you try the latest released version to see if the problem has been fixed?

**Comment by moojjoo** [comment]
mads - This is fine on my part.  As displayed above the GUI changed and I also had to restart VS2015, but all is working fine now.  Thanks for checking in.

**Comment by shawnlehner** [comment]
I actually re-installed the dev station that was having this issue so I honestly couldn't tell you if it was fixed by the re-install, or a new version I got via the extension manager, but it is all working fine now.

Thanks!

**Comment by madskristensen** [comment]
Thanks for verifying

**Comment by gonzalocalandria-xcentium** [comment]
I'm having the issue with version 2.4.340! I'm modifying the js file, when i save it and click Rebundle-file a message shows up saying that the file has unsaved changes inside the editor and has been changed externally asking to reload again without the changes so i cannot change anything.
