### ISSUE TITLE
Minification error

### ISSUE THREAD

**Issue by Gambero81** [madskristensen/BundlerMinifier#131]
[ApprovalRequestDialog.zip](https://github.com/madskristensen/BundlerMinifier/files/312152/ApprovalRequestDialog.zip)

running minify on a specific html file in vs2015 the min.html file result without class attribute quote on img element

I attach the html sample:

as you can note, the code:

    <img ng-src="{{ model.boolToSwitchImage(model.args.shareApprovalInfoAmongRecipients) }}" ng-click="model.args.shareApprovalInfoAmongRecipients = !model.args.shareApprovalInfoAmongRecipients" class="dpg-switch-image" />

is minified as:

    <img ng-src="{{ model.boolToSwitchImage(model.args.shareApprovalInfoAmongRecipients) }}" ng-click="model.args.shareApprovalInfoAmongRecipients = !model.args.shareApprovalInfoAmongRecipients" class=dpg-switch-image>

causing error on 

    class="dpg-switch-image" 

translated as 

    class=dpg-switch-image

**Comment by madskristensen** [comment]
Please open this bug on the [NUglify repo](https://github.com/xoofx/NUglify), if this wasn't fixed in the 2.0 release
