### ISSUE TITLE
Right-click Minify on JS clobbers existing bundle

### ISSUE THREAD

**Issue by Bokkeman** [madskristensen/BundlerMinifier#132]
### Installed product versions
- Visual Studio: 2015 Ent
- This extension: 1.9.157

### Description & steps to recreate
If you create a Javascript bundle with e.g. name `bundle.js` then later right-click on the generated bundle.js in the Solution Explorer and choose `Minify File` from the context menu, it will overwrite the existing bundle definition in `bundleconfig.json`, without warning, with a new minification rule.

### Expected behavior
It should warn you that there is already a bundling rule with this target and that the target will automatically be minified.

**Comment by madskristensen** [comment]
This should be fixed in the latest [CI build](http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/). Please try it out and verify that it works
