### ISSUE TITLE
Knockout comments do not get preserved

### ISSUE THREAD

**Issue by rudym87** [madskristensen/BundlerMinifier#135]
### Installed product versions
- Visual Studio: 2015 Community
- This extension: 2.0.238

### Description
Contrarily to the tooltip which appears when editing bundleconfig.json, the option `removeHtmlComments` (which defaults to true) strips out Knockout.js containerless comments.

### Steps to recreate
Create an HTML file like this:
````html
<div>
    <!--ko if: observable-->
    <p></p>
    <!--/ko-->
</div>
````
### Current behavior
````html
<div><p></p></div>
````

### Expected behavior
````html
<div><!--ko if:observable--><p></p><!--/ko--></div>
````

**Comment by madskristensen** [comment]
Can you please open the bug on NUglify to add Knockout comment support like AjaxMin had it? https://github.com/xoofx/NUglify

**Comment by rudym87** [comment]
Done, linkback: https://github.com/xoofx/NUglify/issues/8.

**Comment by madskristensen** [comment]
@rudym87 Thanks

**Comment by madskristensen** [comment]
Fixed in NUglify
