### ISSUE TITLE
Minification checks out from source control identical files

### ISSUE THREAD

**Issue by IlBaffo** [madskristensen/BundlerMinifier#139]
### Installed product versions
- Visual Studio: 2015 Community
- This extension: 2.0.235 (and build from source at commit 2b3a1226f305d2c26fce9a5863debf9e7e2195f2)

### Description
Minified and source files are checked out from Team Foundation even if file contents are the same.

### Steps to recreate
1. Take a solution from source control TFS
2. Ensure that target files are not checked out
3. Right click on a bundleconfig.json and launch minify of any file (css/js/html)

### Current behavior
Files are checked out from source control and the "pending changes" window and, with the "ask for checkout" option turned on, a confirm window is displayed for every file to be checked out (just imagine having 30/40 files in your bundle...).

### Expected behavior
Unchanged files should not be  checked out from source control.

### Suggested solution
I have quickly debugged the extension and I have found that the 2 functions:

- RemoveReadonlyFlagFromFile
- CheckFileOutOfSourceControl

are called in an event handler even for files that are not changed.

Adding a conditional to not call those functions like `if (e.ContainsChanges)` seems to fix the issue but it is just a workaround.

These functions are the ones that are causing the behaviour:
https://github.com/madskristensen/BundlerMinifier/blob/2b3a1226f305d2c26fce9a5863debf9e7e2195f2/src/BundlerMinifier.Core/Program.cs#L235-L244
https://github.com/madskristensen/BundlerMinifier/blob/2b3a1226f305d2c26fce9a5863debf9e7e2195f2/src/BundlerMinifierVsix/BundleService.cs#L23-L27

**Comment by PRISMAY** [comment]
I had created a duplicate, #141, which I closed but I'm also having the same issue.

Visual Studio: VS 2015 Enterprise - 14.0.25123.00 Update 2
This extension: 2.1.255

**Comment by madskristensen** [comment]
Please help verify the fix by installing the latest [CI build](http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/)

**Comment by PRISMAY** [comment]
Thank you for the quick turnaround.  I can confirm the issue is fixed in the CI build provided.  Thank you very much.
