### ISSUE TITLE
"Unable to add project item" when adding more bundles

### ISSUE THREAD

**Issue by dandrayan** [madskristensen/BundlerMinifier#14]
Steps to reproduce:
1. Open a solution that already has bundles
2. Create and save a new bundle
3. Receive error:
"Unable to add project item
[path to bundleconfig.json]
ADDRESULT_Cancel"

I am using this within the context of a Cordova project and committing code in TFS 2013. Currently to work around this error, I copy out the contents of the bundleconfig.json file, delete it, create the new bundle, and manually edit the new bundleconfig.json file to include the copied contents.

**Comment by madskristensen** [comment]
Thanks for submitting the bug. I haven't tested it on Cordova projects yet. Can you repro the issue if the files in question are not under source control?

**Comment by dandrayan** [comment]
Yes, I just tried a copy of the same solution with all source control bindings removed from project and solutions files and still received the same error message.

**Comment by madskristensen** [comment]
Ok, I think I know how to fix this. Give me 30 minutes and I'll have updated bits ready for you to try out

**Comment by madskristensen** [comment]
Can you please send me the project type guid inside the .jsproj file of your project? Or just the entire .jsproj file. Email to madsk at Microsoft com

**Comment by madskristensen** [comment]
never mind.

**Comment by madskristensen** [comment]
Version 1.0.30 will be available in a few minutes here http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/

It should have the fix so you no longer get the error. Please let me know if it did the trick and thanks again for reporting this!

**Comment by madskristensen** [comment]
It's ready for testing now

**Comment by dandrayan** [comment]
Worked like a charm! Thanks for the quick turnaround time!
