### ISSUE TITLE
Framework net461 not supported

### ISSUE THREAD

**Issue by peterorjeff** [madskristensen/BundlerMinifier#140]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 2.0.235

### Description
Adding the `"BundlerMinifier.Core": "2.0.235"` dependency results in Package Restore Failed
> NU1002: The dependency BundlerMinifier.Core 2.0.235 does not support framework .NETFramework, Version=v4.6.1

Here is my frameworks section from project.json
```json
"frameworks": {
	"net461": { }
}
```

### Steps to recreate
1. Use only net461 framework
2. Add BundlerMinifier.Core dependency

### Current behavior
Receiving framework not supported error.

### Expected behavior
Package restore to complete without error.

### Questions
1. Is there anything I can do as a workaround?
2. Are there any plans to support this framework?

**Comment by madskristensen** [comment]
I can't repro this. Did you add it to the `"tools"` section or under `"dependencies"`?

**Comment by peterorjeff** [comment]
I'm adding under `"dependencies"`

I was just using the `"version"`, so I tried pasting in your snippet and got the same error:

> Package BundlerMinifier.Core 2.0.235 is not compatible with net461 (.NETFramework,Version=v4.6.1). Package BundlerMinifier.Core 2.0.235 supports: netcoreapp1.0 (.NETCoreApp,Version=v1.0)
    One or more packages are incompatible with .NETFramework,Version=v4.6.1.

**Comment by madskristensen** [comment]
It should be in the `"tools"` section and not `"dependencies"`

**Comment by madskristensen** [comment]
See this https://github.com/madskristensen/BundlerMinifier/wiki#command-line-interface-net-core

**Comment by peterorjeff** [comment]
That did the trick, I was thinking that I first needed to add the dependency, then the tools. Good to know.

Thanks for the super quick response and the great tool, time to get rid of all those node_modules now!

**Comment by madskristensen** [comment]
Glad I could help. It will be possible to reference the package from `"dependencies"` in the future
