### ISSUE TITLE
Minifying One File Causes ALL Files In bundleconfig.json To Get Checked Out and Updated

### ISSUE THREAD

**Issue by PRISMAY** [madskristensen/BundlerMinifier#141]
### Installed product versions
- Visual Studio: VS 2015 Enterprise - 14.0.25123.00 Update 2
- This extension: 2.1.255

### Description
Updated to latest version today and now every time I minify a JS file, EVERY file already referenced in bundleconfig.json gets automatically checked out and updated.  We have hundreds of JS files so this not good.

### Steps to recreate
1. Add several JS files and minify them
2. Check them into your source control (we use TFS)
3. Now check out bundleconfig.json
4. Add a new JS file and then minify
5. Upon minifying latest file, you'll see all the files referenced in bundleconfig.json get checked out and updated.

### Current behavior
The behavior is the same as described above.

### Expected behavior
I expect the file or set of files that I just minified to be the only files affected/impacted.  Any other file referenced should NOT be automatically updated and, in the case where it's source controlled, it should get checked out.

It would be nice to have a setting that can be configured, e.g., update all bundles upon minification, or something similar.

**Comment by IlBaffo** [comment]
Did you perhaps look at the opened issues before creating a new one?
https://github.com/madskristensen/BundlerMinifier/issues/139

**Comment by PRISMAY** [comment]
Wow, I can't believe I missed that one.  I'll close this one since it's a duplicate and I'll add a comment to the #139.  Thanks.
