### ISSUE TITLE
ERROR: There is an error in the bundleconfig.json file. This could be due to a change in the format after this extension was updated

### ISSUE THREAD

**Issue by PRISMAY** [madskristensen/BundlerMinifier#142]
### Installed product versions
- Visual Studio: VS 2015 Enterprise - 14.0.25123.00 Update 2
- This extension: 2.1.255

### Description
I needed to minify a bunch of JS files after I upgraded the web extension.  While doing this, I used Alt-Shift-F to minify each file (this does NOT automatically check out the file and update it) and after all files I right-click bundleconfig.json and use the "Update Bundles" context menu to actually update the files which also checks them out of source control.

While doing the process above, I noticed that VS started to lag and slowed down quite a bit and then I started getting dialogs with the "There is an error in the bundleconfig.json file. This could be due to a change in the format after this extension was updated" message.  This didn't seem to have done anything to my process after checking the files, but it was concerning.

### Steps to recreate
I tried to recreate with a new solution but I could not.  I think it would be difficult to do unless I create one as large as our current solution.  I just used a templated web project and added 30+ JS files and the error never popped up.  Also, the VS performance lag didn't seem to show itself but I think that's also due to how large the solution is and how many projects in that solution.

Note in the sample solution, when using Alt-Shift-F, the process did check out the .js and .min.js file as opposed to that not happening in our large solution as described above.

### Current behavior
As more JS files are minified with Alt-Shift-F, the "There is an error in the bundleconfig.json file. This could be due to a change in the format after this extension was updated" message dialog pops up at unspecified intervals (seems random).

### Expected behavior
As in the behavior of the new small solution, Alt-Shift-F should minify the JS file (updating any existing files, i.e., .min.js) and check out from source control if source controlled.

**Comment by madskristensen** [comment]
Can you try the just-released new version and see if the issue still repros? I might have fixed this as a side effect of fixing another bug

**Comment by PRISMAY** [comment]
I just installed the official release and it looks like .258 has fixed this issue.  Thank you so much for the quick turnaround on this bug and #139 .  Very much appreciated.

**Comment by madskristensen** [comment]
Awesome. Thanks for verifying

**Comment by homer1994** [comment]
@madskristensen, unfortunately, this is still happening for me, in the latest version, 2.2.307. Happens to other people who work on the same project. Any way to get more details of this error, to hopefully help me pinpoint the part of bundleconfig.json that Bundler & Minifier doesn't like? There's nothing obvious and the bundleconfig.json is too long to try to figure this out by adding/removing lines. BundleMinifier.exe runs just fine from command line and there are no errors, but it still throws errors in Visual Studio.
![bundlererrors](https://cloud.githubusercontent.com/assets/10173636/20901307/ec521f18-baff-11e6-9f6a-05b3dfe408f9.PNG)

**Comment by arhill05** [comment]
I'm in the same boat as @homer1994. I'll get up to 12 different pop ups _every single time_ I save changes. It's even worse when I try to build.

Our bundleconfig.json is very large and continues to grow so it's not something we can just remove single lines at a time from to figure it out.

**Comment by homer1994** [comment]
I found a workaround that makes the error popup go away for us. It appears that the "Produce Output Files" switch causes it, when set to true. Disabling it made them go away. Just right-click bundleconfig.json in Solution Explorer, click "Bundler & Minifier" and then turn off the switch in the popup as well as in the Settings. Requires a Visual Studio restart for the changes to take effect:
![bundleconfigwarningsworkaround](https://cloud.githubusercontent.com/assets/10173636/20982621/5ffd7268-bc87-11e6-80c4-122aada7b124.PNG)

**Comment by arhill05** [comment]
@homer1994 you are an amazing person. Thank you for saving my entire team a huge headache until a real fix can be implemented.

**Comment by ChrisBurgdorff** [comment]
I was getting that same error popup.  I tried the workaround, which is effective in silencing the error message, but now when I make changes to one of my JS, CSS, or TS files, the changes don't appear in the generated javascript that runs on the site.  Anyone have any ideas why this is the case?

**Comment by 304NotModified** [comment]
I don't have that issue, but the annoying popups are still there. Seems to be related to switching got branches (outside VS)

**Comment by hardhub** [comment]
Same issue with VS2017 on solution startup.

**Comment by gtdtm** [comment]
@hardhub FWIW, I ran into this problem in VS2017 as well and noticed that it occurred if I tried bundling and overwriting the same file name. In other words using the same outputFileName as one of the inputFiles. So if I had one of the inputFiles as wwwroot/js/site.js and the outputFileName as wwwroot/js/site.js I got this error. I assume it's because it can't overwrite itself. I obviously don't know how your code is structured, but thought I'd share my facepalm in case it was the same.

**Comment by DDDN** [comment]
Also got this error. Use this format to get rid of it.

[
  {
    "outputFileName": "wwwroot/css/bootstrap.min.css",
    "inputFiles": [
      "lib/bower/bootstrap/dist/css/bootstrap.css"
    ],
    "minify": {
      "enabled": true,
      "renameLocals": true
    },
    "sourceMap": false
  }
]

**Comment by cderosaOutreach** [comment]
@DDDN I currently use the square brackets first format but still get the pop-up...
![image](https://user-images.githubusercontent.com/26577418/29374034-41606f20-826d-11e7-9dbb-e4706472cfa0.png)

**Comment by hardhub** [comment]
I assume I get this error when source files required for bundling are updated (by bower and Co).
But if it is the reason and error really occurs (but with file) then message "error in bundleconfig.json" sounds wrong.

**Comment by 304NotModified** [comment]
We have also still this issue.

**Comment by LordDelacroix** [comment]
using version 2.5.359 and I have this problem as well ... it started yesterday and today, I can't even USE VS 2017 without having to kill it for the damned dialogs that start as SOON as I open my project!

**Comment by 304NotModified** [comment]
issue is also still here. The config is correct - double checked it.

I think it goes wrong when we switch between branches in git. I think it temporary empty or something like that.

**Comment by LordDelacroix** [comment]
For me it's got nothing to do with switching branches.  I simply right-click on a JS or CSS file and ask it to minimize the file and BAMPF - eeeerrrors abound...nearly 40 of those blasted dialogs bitching about the file format.

**Comment by 304NotModified** [comment]
@LordDelacroix maybe create a new issue if you could easily reproduce this

**Comment by chaffee007** [comment]
I also am having the issue, but I am unable to recreate it on demand.  It appears at unsuspecting times.  However the bundled file is updated correctly.

**Comment by Andre-de-Vos** [comment]
When using this wildcard for inputfiles (e.g. "wwwroot/css/**/*(*.css|!(*.min.css)") I got the error, but when 
- specifying  the file(s) e.g. "wwwroot/css/site.css"  
- using this wildcard  "wwwroot/css/**/*.css" 
the error is gone. So possible wrong use of wildcard?
