### ISSUE TITLE
Gzip option results on "Unexpected end of file" files

### ISSUE THREAD

**Issue by ealsur** [madskristensen/BundlerMinifier#143]
### Installed product versions
- Visual Studio: 2015 Update 3 Community
- This extension: 2.1.255

### Description
If you check the [bundleconfig.json](https://github.com/ealsur/minicompiler/blob/master/src/minicompiler/bundleconfig.json), I'm minifying and gzipping CSS and JS files. The minified (.min.css and .min.js) files are OK. But the Gzip ones (.min.css.gz and .min.js.gz) are flawed somehow. If they are served to a client on the browser they don't work, if you try to open them with a Zip manager (WinRar for example) it shows an "Unexpected end of file" error. 

### Steps to recreate
Repro repo here: https://github.com/ealsur/minicompiler

### Current behavior
The .gz file has an error in its generation.

### Expected behavior
The .gz files should be openable correctly by supported Gzip file managers and received correctly by client browsers.

**Comment by madskristensen** [comment]
You need to serve them with the right HTTP headers specific to pre-gzipped css/js files. Are you doing that?

**Comment by ealsur** [comment]
I'm using the same logic to alter the HTTP headers that we are using on a gulp-gzip scenario.
On the [Startup.cs](https://github.com/ealsur/minicompiler/blob/master/src/minicompiler/Startup.cs#L24) I'm using a middleware to catch that.

**Comment by madskristensen** [comment]
Strange. Here's how it creates the .gz file:

```C#
using (var sourceStream = File.OpenRead(sourceFile))
using (var targetStream = File.OpenWrite(gzipFile))
{
    var gzipStream = new GZipStream(targetStream, CompressionMode.Compress);
    sourceStream.CopyTo(gzipStream);
}
```

**Comment by ealsur** [comment]
Sounds good enough. I don't know then why would the file appear with an error :( 
Did you manage to reproduce it with my repo? Maybe it's something from my setup?

**Comment by ealsur** [comment]
When using Gulp-gzip I found out that they had several [Levels](https://nodejs.org/api/zlib.html#zlib_memory_usage_tuning) based on the internal Zlib library, some of them would compress the files in such a way that it would break them. What is weird is that up to the minification, it works great, but the .gz file comes out wrong.

**Comment by madskristensen** [comment]
Ok, I think I've got a fix. I can now open the .gz file in 7zip correctly

**Comment by madskristensen** [comment]
Please help verify the fix by installing the latest [CI build](http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/)

**Comment by ealsur** [comment]
You sir are a titan.

**Comment by madskristensen** [comment]
So it worked?

**Comment by ealsur** [comment]
Yes indeed!

**Comment by madskristensen** [comment]
Awesome. Thanks for reporting the issue and testing the fix!!
