### ISSUE TITLE
Visual Studio MEF Can't load BundlerMinifier

### ISSUE THREAD

**Issue by ayseff** [madskristensen/BundlerMinifier#144]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: 2.1.255

### Description
This is from my %AppData%\Microsoft\VisualStudio\14.0\ActivityLog.xml file:

CreateInstance failed for package [BundlerMinifierPackage]Source: 'mscorlib' Description: Could not load file or assembly 'file:///C:\USERS\x\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\aoa5pksq.0cr\BundlerMinifierVsix.dll' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\USERS\x\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\aoa5pksq.0cr\BundlerMinifierVsix.dll' or one of its dependencies. The system cannot find the file specified. File name: 'file:///C:\USERS\x\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\aoa5pksq.0cr\BundlerMinifierVsix.dll' at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark) at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence) at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo) at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by madskristensen** [comment]
It looks like a classic case of MEF cache corruption in VS. It has nothing to do with this extension, but VS that gets confused. Here's how to clean the MEF cache https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd

**Comment by ayseff** [comment]
Thanks, @madskristensen.  I actually couldn't get that extension to work either.  No MEF error; it simply doesn't show up in the Tools Menu.  Notwithstanding, I manually deleted the ComponentModelCache folder from disk and restarted VS but that still didn't fix the original issue. :(
