### ISSUE TITLE
New Version cannot generate file output same name with input

### ISSUE THREAD

**Issue by nbhuy89** [madskristensen/BundlerMinifier#152]
Hi, 
I am using
- Visual Studio: 2015 Professional
- This extension: 2.1.258

My config

  {
        "outputFileName": "_Menu/Resources/Menu.js",
        "inputFiles": [
            "_Menu/Resources/Menu.js"
        ]
    },

Currently extension does not generate Menu.min.js like previous version.

I have to change config to 
  {
        "outputFileName": "_Menu/Resources/Menu.min.js",
        "inputFiles": [
            "_Menu/Resources/Menu.js"
        ]
    },
So it can generate output file.
=> so i must change all config, so awful. :(

**Comment by madskristensen** [comment]
Unfortunately, this was a change that I had to make due to usability issues. Sorry that it forced you to manually update the json file

**Comment by nbhuy89** [comment]
Thank your, I have a request, could you add the install file (.vsix) to Release log page, so we can choose the version to install?
