### ISSUE TITLE
Already minified file being bundled twice (adding .min.min.js)

### ISSUE THREAD

**Issue by rexxmagnus** [madskristensen/BundlerMinifier#155]
### Installed product versions
- Visual Studio: 2015 Community edition (14.0.25422.01 Update 3 - also happened before update 3)
- This extension: 2.1.258

### Description
Added a (non minified) javascript file and minified using the menu option. Correctly auto-added to bundleconfig and xxxx.min.js generated, but on build an additional minified file (and map) are added with xxxx.min.min.js
The xxx.min.js is not mentioned in the bundle config as a file that needs to be minified.

### Steps to recreate
1. Add a new javascript file (in this case it's the last file in the list in a given folder)
2. Minify the file
3. Build the solution
4. Attempted clearing out the minification config for the above file and restarting visual studio then re-minifying, but the behaviour continued.

### Current behavior
Minified file gets added. On build an additional minified file is added with an additional .min in the extension. The .min.min.js file (and map) are not marked for inclusion in the solution unlike the correctly minified file.

### Expected behavior
Minify the file only once and not add xxxx.min.js and xxxx.min.min.js

**Comment by madskristensen** [comment]
Can you please try to update the NuGet package that minifies on build and try again. This issue should have been fixed a while ago

**Comment by madskristensen** [comment]
This has been fixed
