### ISSUE TITLE
Update BundlerMinifier tools package to use new "Tools" package type

### ISSUE THREAD

**Issue by Eilon** [madskristensen/BundlerMinifier#157]
There's a new NuGet feature which allows authors of .NET CLI tools packages to mark their packages with a special “package type”. This package type allows the NuGet UI in Visual Studio to treat the .NET CLI tools package differently than a normal dependency package. In the .NET Core project.json world, this means that the tool will be added to the “tools” node of the project.json. Without the package type, the tool package looks like any other dependency package to NuGet and is therefore installed to the “dependencies” node. It’s important for the tool to be under the “tools” node because this is how new commands in the .NET CLI get lit up.

https://github.com/NuGet/Home/wiki/Package-Type#installation 

Applies to: BundlerMinifier.Core: https://github.com/madskristensen/BundlerMinifier/blob/master/src/BundlerMinifier.Core/project.json

**Comment by ealsur** [comment]
I believe that it [already supports that](https://github.com/madskristensen/BundlerMinifier/wiki#command-line-interface-net-core).
You can hook it up as `dotnet bundle`.

**Comment by Eilon** [comment]
@ealsur this is different and not related to whether the package *is* a tool or not. You are correct that this package already functions as a proper .NET CLI tool. This issue is about giving a hint to NuGet's "package install" logic to automatically reference it as a "tool" package as opposed to a regular "library" package. That's what the related PR does.
