### ISSUE TITLE
duplicate Bundler & Minifier entry in Output window

### ISSUE THREAD

**Issue by scottaddie** [madskristensen/BundlerMinifier#162]
### Installed product versions
- Visual Studio: 2015 Enterprise Update 3
- This extension: 2.1.258

### Description
The "Bundler & Minifier" entry appears twice in the Output window's "Show output from" drop-down.

### Steps to recreate
1. Create a new ASP.NET Core Web Application (.NET Core) with the "StarterWeb" project template
2. Right-click the `bundleconfig.json` file in Solution Explorer and choose **Bundler & Minifier** --> **Convert to Gulp**
3. View the Output window, click the "Show output from" drop-down, and notice there are 2 entries for "Bundler & Minifier".

### Current behavior
There are 2 "Bundler & Minifier" entries in the Output window's "Show output from" drop-down:

![bug](https://cloud.githubusercontent.com/assets/10702007/17182342/c322765c-53e8-11e6-8b3b-6e4d1af76dbc.png)

The output in each appears to be identical.

### Expected behavior
There should never be multiple "Bundler & Minifier" entries in the Output window's "Show output from" drop-down.

**Comment by madskristensen** [comment]
This has been fixed
