### ISSUE TITLE
File Paths on the css files are being changed after bundling

### ISSUE THREAD

**Issue by daskul** [madskristensen/BundlerMinifier#176]
### Installed product versions
- Visual Studio: VS2015 Community
- This extension: 2.1.279
### Description

Changing the relative paths on css/scss files
### Steps to recreate

I have the following directory
--wwwroot
----css
------vendor.css
----js
----fonts
--assets
----bower_components
------mdi
--------css
----------materialdesignicons.css

And the following bundleconfig.js
// Configure bundling and minification for the project.
// More info at https://go.microsoft.com/fwlink/?LinkId=808241

```
[
    {
        "outputFileName": "wwwroot/css/vendor.css",
        "inputFiles": [
            "assets/bower_components/materialize/dist/css/materialize.css",
            "assets/bower_components/mdi/css/materialdesignicons.css"
        ]
    },
    {
        "outputFileName": "wwwroot/css/site.css",
        // An array of relative input file paths. Globbing patterns supported
        "inputFiles": [
            "assets/sass/site.scss"
        ]
    },
    {
        "outputFileName": "wwwroot/js/site.min.js",
        "inputFiles": [
            "wwwroot/js/site.js"
        ],
        // Optionally specify minification options
        "minify": {
            "enabled": false,
            "renameLocals": true
        },
        // Optinally generate .map file
        "sourceMap": false
    }
]

```

I have this snippet on css file  `assets/bower_components/mdi/css/materialdesignicons.css`

```
@font-face {
  font-family: "Material Design Icons";
  src: url("../fonts/materialdesignicons-webfont.eot?v=1.7.12");
  src: url("../fonts/materialdesignicons-webfont.eot?#iefix&v=1.7.12") format("embedded-opentype"), url("../fonts/materialdesignicons-webfont.woff2?v=1.7.12") format("woff2"), url("../fonts/materialdesignicons-webfont.woff?v=1.7.12") format("woff"), url("../fonts/materialdesignicons-webfont.ttf?v=1.7.12") format("truetype"), url("../fonts/materialdesignicons-webfont.svg?v=1.7.12#materialdesigniconsregular") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

When the file is bundled the paths were changed
/\* MaterialDesignIcons.com */

```
@font-face {
  font-family: "Material Design Icons";
  src: url("../../assets/bower_components/mdi/fonts/materialdesignicons-webfont.eot?v=1.7.12");
  src: url("../../assets/bower_components/mdi/fonts/materialdesignicons-webfont.eot?#iefix&v=1.7.12") format("embedded-opentype"), url("../../assets/bower_components/mdi/fonts/materialdesignicons-webfont.woff2?v=1.7.12") format("woff2"), url("../../assets/bower_components/mdi/fonts/materialdesignicons-webfont.woff?v=1.7.12") format("woff"), url("../../assets/bower_components/mdi/fonts/materialdesignicons-webfont.ttf?v=1.7.12") format("truetype"), url("../../assets/bower_components/mdi/fonts/materialdesignicons-webfont.svg?v=1.7.12#materialdesigniconsregular") format("svg");
  font-weight: normal;
  font-style: normal;
}
```
### Current behavior

the paths were changed to accomodate their new location
to:`../../assets/bower_components/mdi/fonts/materialdesignicons-webfont.eot?v=1.7.12`
instead of:`../fonts/materialdesignicons-webfont.eot?v=1.7.12`
### Expected behavior

is there a way to retain the paths?

**Comment by anandtpatel** [comment]
Any update on this ?

**Comment by anandtpatel** [comment]
Did you resolve this issue ? I have same issue with relative path on bundling. 

@daskul  Did you figure the issue ?

**Comment by daskul** [comment]
No I didn't, and I'm not doing .Net projects recently so I can't suggest alternatives.

**Comment by AidanM97** [comment]
For anyone who is still struggling with this, the solution is to add the following lines to your bundleconfig.json:

`"minify": {
      "enabled": true,
      "adjustRelativePaths": false
}`

**Comment by madskristensen** [comment]
@AidenM97 has the right answer

**Comment by minuseight** [comment]
"minify": { "enabled": true, "adjustRelativePaths": false } has to be added to both CSS and JS confiog sections i.e.

[
  {
    "outputFileName": "wwwroot/css/site.min.css",
    "inputFiles": [
      "node_modules/bootstrap/dist/css/bootstrap.css",
      "node_modules/admin-lte/dist/css/adminLTE.min.css",
      "node_modules/admin-lte/dist/css/skins/skin-blue-light.css",
      "node_modules/font-awesome/css/font-awesome.css",
      "wwwroot/css/site.css"
    ],
    "minify": {
      "enabled": true,
      "renameLocals": true,
      "adjustRelativePaths": false
    }
  },
  {
    "outputFileName": "wwwroot/js/site.min.js",
    "inputFiles": [
      "node_modules/jquery/dist/jquery.js",
      "node_modules/bootstrap/dist/js/bootstrap.js",
      "node_modules/admin-lte/dist/js/app.js",
      "wwwroot/js/site.js"
    ],
    "minify": {
      "enabled": true,
      "renameLocals": true,
      "adjustRelativePaths": false
    },
    "sourceMap": false
  }
]
