### ISSUE TITLE
Input File Recursive Globing Support

### ISSUE THREAD

**Issue by ahmedalejo** [madskristensen/BundlerMinifier#19]
This is first non-pull-requested issue.

Should "BundlerMinifier" support input source recursive globing ?

```javascript
[
    {
        "outputFileName": "www/index.html",
        "inputFiles": [
            "app/_index_begin.html",
            "app/_index.html",
            "app/core/, //all .html files in app.core and subfolders
            "app/_index_end.html"
        ]
    }
] 
```

```javascript
[
    {
        "outputFileName": "www/index.html",
        "inputFiles": [
            "app/_index_begin.html",
            "app/_index.html",
            "app/core/directives/login/",            //---|
            "app/core/directives/userprofile/",           |
            "app/core/directives/userphoto/",             | recursive globbing would make this easier. 
            "app/core/directives/currentuser-name/",//---|
             /*...*/
            "app/_index_end.html"
        ]
    }
] 
```

this changed should be of minimal impact from what i´ve seen.
Just would like to change ideas before attempting to provide code changes.

**Comment by madskristensen** [comment]
Support for folder paths such as `app/lib` should already be there

**Comment by madskristensen** [comment]
I just confirmed that folder based bundling works. Is this a different feature and I'm missing the point?

**Comment by ahmedalejo** [comment]
Folder level globing is supported. I meant recursively.
```yaml
dir1:
  - file1.ext
  - file2.ext
  - dir1_2: file3.ext, file4.ext
    - dir1_2_1: file5.ext
```

when i reference the dir folder for globing(bundling) to `output.ext`. i would like to able to specify if:
  only file1.ext and file2.ext are bundled(the current implementation) or
  that file1.ext, file2.ext, file3.ext, file4.ext and file5.ext gets bundled.

Currently this functionality is controlled by the `ProcessBundle` method of the `BundleHandler` class with the following code:

```csharp
if (Directory.Exists(fullPath))
{
    DirectoryInfo dir = new DirectoryInfo(fullPath);
    var files = dir.GetFiles("*" + ext, SearchOption.TopDirectoryOnly);
    inputFiles.AddRange(files.Select(f => f.FullName));
}
```

note the `SearchOption.TopDirectoryOnly`.

this obviously makes the file search to be only one level deep.

**Comment by madskristensen** [comment]
Ahh, having an option to turn recursive on make sense. Good idea

**Comment by madskristensen** [comment]
There is now an option called `recursive` that can be set to `true` to enable this
