### ISSUE TITLE
Incorrect Regexp in generated gulpfile.js

### ISSUE THREAD

**Issue by drewnoakes** [madskristensen/BundlerMinifier#194]
### Installed product versions
- Visual Studio: 2015
- This extension: 2.1.279
### Description

The generated `gulpfile.js` creates regexes to match bundle output files in the `watch` task.

However the regex string is (slightly) invalid. 
### Steps to recreate
1. Convert to Gulp
### Current behaviour

Produces incorrect regex string, where period (`.`) is not escaped and EOL is not matched (ie. `.json` files are watched along with `.js`).
### Expected behaviour

Should produce code such as this:

``` js
gulp.task("watch", function () {
    getBundles(/\.js$/).forEach(function (bundle) {
        gulp.watch(bundle.inputFiles, ["min:js"]);
    });

    getBundles(/\.css$/).forEach(function (bundle) {
        gulp.watch(bundle.inputFiles, ["min:css"]);
    });

    getBundles(/\.html$/).forEach(function (bundle) {
        gulp.watch(bundle.inputFiles, ["min:html"]);
    });
});

function getBundles(outputFileNameRegex) {
    return bundleconfig.filter(function (bundle) {
        return new RegExp(outputFileNameRegex).test(bundle.outputFileName);
    });
}
```

Note how regex literals are passed `/\.css$/` which is clearer and highlighted in the IDE. The period is properly escaped (previously the unescaped dot would have matched any character). There's also an end-of-line marker in the regexes above. This might break valid cases, but I cannot think of any.

**Comment by scottaddie** [comment]
@madskristensen Should this issue be closed now that the associated PR is merged?
