### ISSUE TITLE
Exception User canceled out of save dialog

### ISSUE THREAD

**Issue by totpero** [madskristensen/BundlerMinifier#202]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: 2.1.279

### Description
Exception in output window 

### Steps to recreate
1. Open Task Runner
2. Right click from JavaScript in bundleconfig.json
3. Bindings -> Check After Build
4. to recreate

### Current behavior
```
11/3/2016 1:24:57 PM: System.Runtime.InteropServices.COMException (0x8004000C): User canceled out of save dialog (Exception from HRESULT: 0x8004000C (OLE_E_PROMPTSAVECANCELLED))
   at EnvDTE.ProjectItems.AddFromFile(String FileName)
   at BundlerMinifierVsix.ProjectHelpers.AddNestedFile(String parentFile, String newFile, Boolean force) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Helpers\ProjectHelpers.cs:line 138

```

### Expected behavior
No exception

**Comment by scottaddie** [comment]
@totpero I'm unable to reproduce this with the latest version of the extension (v2.2.307). Have you tried using that version already?

**Comment by dammitjanet** [comment]
Might this be related to this Issue #201 that I raised, the same function calls are involved.

**Comment by totpero** [comment]
@scottaddie only one time i get this error.

**Comment by marcusobrien** [comment]
Seen after using Visual Studio 2019 Community - creating a new Python project for Machine Learning using the cookie cutter for a classifier template.
Microsoft Visual Studio User canceled out of save dialog (Exception from HRESULT: 0x8004000C (OLE_E_PROMPTSAVECANCELLED))

**Comment by itskhurram** [comment]
i am getting the same error when i try to create python project from existing source.

**Comment by yellow444** [comment]
And me getting the same error when i try to create python project from existing source.

**Comment by BIJINPALAKKAL** [comment]
Please make sure your project file is not locked.
You can check it by trying to edit the project file (.csproj file). If this file is locked, you cannot add the dependencies.

![projectfile](https://user-images.githubusercontent.com/26296106/111413686-bcaceb00-8704-11eb-8ae8-84751c783661.JPG)

Tell the person who locked the file to check in or undo the project file and then try to add the dependency
