### ISSUE TITLE
Invalid Path in Post Build event error on BundleMinifier project

### ISSUE THREAD

**Issue by dammitjanet** [madskristensen/BundlerMinifier#207]
### Installed product versions
- Visual Studio: 2016 Enterprise
- This extension: 2.2.307

### Description
The post build script has issue with $(MSBuildProjectDirectory) path containing spaces

### Steps to recreate
1. Clone to a Directory containing spaces
2. Build - build fails as below
3. Clone to a Directory without spaces
4. Build succeeds.

### Current behavior
1>  Running Code Analysis...
1>  Code Analysis Complete -- 0 error(s), 0 warning(s)
1>  'C:\Users\stuwilson\Documents\Visual' is not recognized as an internal or external command,
1>  operable program or batch file.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4714,5): error MSB3073: The command "C:\Users\stuwilson\Documents\Visual Studio 2015\Projects\BundlerMinifier\src\BundlerMinifier\..\..\packages\NuGet.CommandLine.2.8.5\tools\nuget.exe pack .\msbuild\BuildBundlerMinifier.nuspec -Verbosity quiet" exited with code 9009.

### Expected behavior
It should build correctly

**Comment by dammitjanet** [comment]
I've got a branch and pull request ready to fix this.

**Comment by scottaddie** [comment]
@dammitjanet Is it safe to close this one now?

**Comment by dammitjanet** [comment]
aye, thanks
