### ISSUE TITLE
Versions conflict. Attempt to download not existing version of BuildBundlerMinifier

### ISSUE THREAD

**Issue by matthiaslischka** [madskristensen/BundlerMinifier#209]
### Installed product versions
- Visual Studio: Enterprise 2015
- This extension:  2.2.307

### Description
The extension tries to download "BuildBundlerMinifier,2.2.307". There is no such package. Only version 2.2.306.

### Steps to recreate
1. "Enable bundle on build..."
2. allowing BundlerMinifier to download a NuGet package

### Current behavior
System.InvalidOperationException: Package 'BuildBundlerMinifier,2.2.307' is not found in the following primary source(s): (...)

### Expected behavior
Should download BuildBundlerMinifier in the [current version](https://www.nuget.org/packages/BuildBundlerMinifier/) 2.2.306

### Workaround
Install the NuGet package "BuildBundlerMinifier" in version 2.2.306 by hand.

**Comment by matthiaslischka** [comment]
BundleOnBuild.cs line: 96
Apparently the Bundler & Minifier Extensions version and the NuGet Package BuildBundlerMinifiers version should be in sync, which is not the case ATM.  [2.2.307](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.BundlerMinifier) vs. [2.2.306](https://www.nuget.org/packages/BuildBundlerMinifier/)
Not sure how this could happen or how it should be prevented but however, somehow this has a smell. Maybe use ```Version=null``` for ```installer.InstallPackage(...``` to always download latest version or explicitly list the matching BuildBundlerMinifiers version in the Constants.cs instead of using the extensions version number for the NuGet package?

BR Matthias

**Comment by AnthonyOSX** [comment]
2 months later and this still isn't fixed. For something that is now recommended over Gulp you would think Microsoft would actually verify the stuff they tell you to use works.

**Comment by matthiaslischka** [comment]
Do they recommend?! Kinda thought this is the oldschool solution from long before gulp, webpack and co.

**Comment by AnthonyOSX** [comment]
http://www.talkingdotnet.com/gulp-is-no-longer-default-choice-asp-net-core/
