### ISSUE TITLE
VS2017 - don't see "web compiler" context menu

### ISSUE THREAD

**Issue by rbrian** [madskristensen/BundlerMinifier#211]
### Installed product versions
- Visual Studio: 2017 RC
- This extension: 2.2.309

### Description
right-clicking on a .less file in the solution explorer doesn't show "Web Compiler" menu as it does in VS2015. also, files that have been tagged to automatically compile in VS2015 don't rebuild in 2017.

**Comment by matthiaslischka** [comment]
"web compiler" and "bundler minifier" are two different tools.
check out: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.WebCompiler

**Comment by rbrian** [comment]
My bad. Will go report it in the right place.
