### ISSUE TITLE
No executable found matching command "dotnet-bundle" with Framework 4.6.1 project

### ISSUE THREAD

**Issue by sanchobear** [madskristensen/BundlerMinifier#213]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 2.2.307
### Description
Using an ASP.NET Web Application (.Net Framework 4.6.1) with bundle.json gives error message 
No executable found matching command "dotnet-bundle", although the executable is in bin\Debug\net461\win7-x64 directory

### Steps to recreate
1. project.json
  "dependencies": {
    "AutoMapper": "5.2.0",
    "bootstrap": "3.3.7",
    "bootstrap.sass": "4.0.0-alpha3",
    "BuildBundlerMinifier": "2.2.306",
...
"tools": {
  "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
  "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
  "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
    "version": "1.1.0-preview4-final",
    "imports": [
      "portable-net45+win8"
    ]
  }
},
"scripts": {
    "precompile": ["dotnet bundle"],
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }

2. bundle.json
// Configure bundling and minification for the project.
// More info at https://go.microsoft.com/fwlink/?LinkId=808241
[
  {
    "outputFileName": "wwwroot/css/site.min.css",
    // An array of relative input file paths. Globbing patterns supported
    "inputFiles": [
      "wwwroot/css/site.css"
    ]
  },
  {
    "outputFileName": "wwwroot/js/site.min.js",
    "inputFiles": [
      "wwwroot/js/site.js"
    ],
    // Optionally specify minification options
    "minify": {
      "enabled": true,
      "renameLocals": true
    },
    // Optinally generate .map file
    "sourceMap": false
  }
]

### Current behavior
Build Solution gives error: 
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : No executable found matching command "dotnet-bundle"
no min.js/css versions created

### Expected behavior
site.min.css and site.min.js are created without error message during build.

**Comment by ShayneSmyth** [comment]
I too have this problem. I have had numerous problems after switching to framework "net461". Everything worked fine on "net452".

**Comment by sanchobear** [comment]
Finally, I got it resolved:
Reason is, that VS package upgrade sets 
    "BuildBundlerMinifier": "2.4.337",
    "BundlerMinifier.Core": "2.4.337",
into the dependencies section, whereas the "BundleMinifier.Core" must be located in the "tools" section!

So simply moving the  "BundlerMinifier.Core": "2.4.337" line from dependencies into tools section of project.json fixes it.

@owner: Should improve package installer.
