### ISSUE TITLE
minify html lost something

### ISSUE THREAD

**Issue by hg533** [madskristensen/BundlerMinifier#216]
### Installed product versions
- Visual Studio: [ 2015 Professional]
- This extension: [2.2.307]

### Description
my html has line(with angularjs ):`<report print="true" ></report>`
when i minify it ,the line changed to:`<report print></report>`
it lost the:="true"
my app run error

**Comment by scottaddie** [comment]
@hg533 Try using the `collapseBooleanAttributes` and `removeQuotedAttributes` properties in `bundleconfig.json`. Here's an example:

```json
  {
    "outputFileName": "index.min.html",
    "inputFiles": [ "index.html" ],
    "minify": {
      "enabled": true,
      "collapseBooleanAttributes": false,
      "removeQuotedAttributes": false
    }
  }
```

In case you're wondering, Visual Studio reads the JSON schema located [here](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/bundleconfig.json). That's a great place to look for valid properties in `bundleconfig.json`.

**Comment by hg533** [comment]
@scottaddie That's great!Thank u!but,Did I need to add this to every mini file?

**Comment by scottaddie** [comment]
@hg533 Even though file glob patterns are supported, I don't believe it's possible to achieve what you're after. In other words, you'd have to define these properties for every `.min` file. Issue https://github.com/madskristensen/BundlerMinifier/issues/147 is asking for the same feature.

You can achieve this using a tool like Gulp or Webpack. In fact, this extension will create a `gulpfile.js` that reads your `bundleconfig.json` file.

**Comment by hg533** [comment]
@scottaddie  Thant's a good idea.thank u very much!
