### ISSUE TITLE
Issue Minifying CSS files with css variables

### ISSUE THREAD

**Issue by koimad** [madskristensen/BundlerMinifier#218]
### Installed product versions
- Visual Studio:  2015 
- This extension: 2.2.307

### Description
I'm unable to minify any css files with css variablke defined.

### Steps to recreate
1. Create css file with the following content 
:root {
    --background:#006b6b;
    --textcolour:#ffffff;
    --hoverOverColour:#FFC100;
    --gradientDarkColour:#004a4a;
    --gradienDarkHoverColour:#005a5a;
    --gradientLightColour:#008b8b;
    --gradientLightHoverColour:#009b9b; 
    --topMenuTextColour:#003b3b;
   }

2. right click the file in visual studio to minify.
3. in error window get the following.
Severity	Code	Description	Project	File	Line	Suppression State
Error		(Bundler & Minifier) Expected semicolon or closing curly-brace, found '-'		C:\Users\Brian\documents\visual studio 2015\Projects\SchoolCMS\SchoolCMS\css\site-colours.min.css	

### Current behavior
Code does not recognise css variables

### Expected behavior
recognise variables and apply across all files.

**Comment by scottaddie** [comment]
CSS variables don't seem to be supported by NUglify, which handles the CSS minification in this extension. I've logged an issue [here](https://github.com/xoofx/NUglify/issues/17).

**Comment by ipjohnson** [comment]
This issue looks to be open for 2 years. Is there a plan to address this or move away from NUglify as the main developer has stated he doesn't have any interest in fixing the problem?

**Comment by FreeManTR** [comment]
I have same error. Any updates?

**Comment by aaronhudon** [comment]
@FreeManTR I think the solution is going to be to switch to Gulp

**Comment by ipjohnson** [comment]
@madskristensen any thoughts on the topic as the main developer? Is the answer microsoft is not interested in supporting this and we should move off to another product that will be maintained?

**Comment by KiarashS** [comment]
Also i have same error. Any updates?

**Comment by kmcconnell** [comment]
The only way I could keep working was to move to using Gulp.

**Comment by BLITZandKILL** [comment]
So are we stuck with this issue forever?

**Comment by lepipele** [comment]
@BLITZandKILL seems so...

**Comment by lepipele** [comment]
Hey guys... fix is here -> https://github.com/madskristensen/BundlerMinifier/issues/306

**Comment by lepipele** [comment]
2.6.375 out, fixes this problem: https://www.nuget.org/packages/BuildBundlerMinifier/

**Comment by jaoord** [comment]
This seems to be broken again in the latest version (2.9.406)

**Comment by rohitvipin** [comment]
I can reproduce this on VS 2019 👎

**Comment by xbaha** [comment]
i have same problem for this css code:
    filter: progid: DXImageTransform.Microsoft.Alpha(Opacity=40);

**Comment by adlesh** [comment]
This may be separate, but this felt like a good place to do put this. If you run into a similar error, for example mine was "Expected semicolon or closing curly-brace, found '@state-text-danger'". Simply remove the @ and wrap the left over in var(--state-text-danger). This allowed me to minify and bundle with no issue.
