### ISSUE TITLE
Missing menu option for .js

### ISSUE THREAD

**Issue by kfrancis** [madskristensen/BundlerMinifier#22]
Hey,

Question - this extension does allow you to minify plain javascript files but the menu option doesn't show when you right-click on the nested js output of a typescript file - can that be added, so that those .js files can be minified as expected?

**Comment by madskristensen** [comment]
The file has to be included in the project for the right-click menu to work. Also, some project systems in Visual Studio doesn't play nice with nested files, so beware of potential differences between ASP.NET, Cordova, etc.
