### ISSUE TITLE
Package 'BuildBundlerMinifier,2.2.307' is not found

### ISSUE THREAD

**Issue by maverix** [madskristensen/BundlerMinifier#225]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 2.2.307

### Description
When I right click on the bundleconfig.json file and select the 'enable bundle on build' option from the bundle context menu, there is an error downloading the BuildBundlerMinifier package from nuget:

`System.InvalidOperationException: Package 'BuildBundlerMinifier,2.2.307' is not found in the following primary source(s): 'https://nuget.org/api/v2/,https://api.nuget.org/v3/index.json,https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/,C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'. Please verify all your online package sources are available (OR) package id, version are specified correctly.`

I'm behind a proxy at work, and I suspect this might be causing the issue.  Nuget works fine in Visual studio.

**Comment by 304NotModified** [comment]
there is no 2.2.307 on nuget? (also not hidden)

![image](https://cloud.githubusercontent.com/assets/5808377/22290086/476e066a-e2ff-11e6-8ff2-998f43909f7c.png)

**Comment by simonech** [comment]
Indeed had the same problem: when enabling the "Enable bundle on build" it tries to download version 307 when the latest available on Nuget is 306

**Comment by AnthonyOSX** [comment]
#209
