### ISSUE TITLE
Support BuildBundlerMinifier on Microsoft.NET.Sdk for .NET Core

### ISSUE THREAD

**Issue by natemcmaster** [madskristensen/BundlerMinifier#230]
### Installed product versions
dotnet-cli 1.0.0-rc3-004350

### Description
In MSBuild 15 projects, BundlerBuildTask is imported when the BuildBundlerMinifier  package is referenced, but the task doesn't support .NET Core.

### Steps to recreate
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
      <PackageReference Include="BuildBundlerMinifier" Version="2.2.306" />
   </ItemGroup>
</Project>
```

dotnet restore
dotnet build

### Current behavior
UsingTask fails to load because it isn't compatible with MSBuild 15 and .NET Core.

> C:\Users\namc\.nuget\packages\buildbundlerminifier\2.2.306\build\BuildBundlerMinifier.targets(15,5): error MSB4062: The "BundlerMinifier.BundlerBuildTask" task could not be loaded from the assembly C:\Users\namc\.nuget\packages\buildbundlerminifier\2.2.306\build\..\tools\BundlerMinifier.exe. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

### Expected behavior
Works in both VS and dotnet CLI

**Comment by spboyer** [comment]
Fails in RC4 as well. 

### Installed product versions
1.0.0-rc4-004734
macOS Sierra 10.12.2

### Steps to recreate
```
$ dotnet new mvc --auth None --framework netcoreapp1.1
$ dotnet add package BuildBundlerMinifier -v 2.2.306
$ dotnet restore
$ dotnet build
```

### Current behavior

>/Users/shayneboyer/.nuget/packages/buildbundlerminifier/2.2.306/build/BuildBundlerMinifier.targets(15,5): error MSB4062: The "BundlerMinifier.BundlerBuildTask" task could not be loaded from the assembly /Users/shayneboyer/.nuget/packages/buildbundlerminifier/2.2.306/build/../tools/BundlerMinifier.exe. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/Users/shayneboyer/github/spboyer/dotnetcore-bundlerminfier/dotnetcore-bundlerminfier.csproj]
/Users/shayneboyer/.nuget/packages/buildbundlerminifier/2.2.306/build/BuildBundlerMinifier.targets(15,5): error MSB4062:  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/Users/shayneboyer/github/spboyer/dotnetcore-bundlerminfier/dotnetcore-bundlerminfier.csproj]

Build FAILED.

**Comment by madskristensen** [comment]
For .NET Core 1.0 you should use version 2.2.301

**Comment by natemcmaster** [comment]
To be clear, the dotnet-bundle tool still works. It's the MSBuild task that doesn't.

**Comment by spboyer** [comment]
What version should you use for 1.1? And is the error a false positive for bundlerminfier?

**Comment by spboyer** [comment]
`dotnet bundle`  returns 

```
No executable found matching command "dotnet-bundle"
```

**Comment by natemcmaster** [comment]
What is in your csproj? Do you have DotNetCliToolReference?

**Comment by spboyer** [comment]
@natemcmaster There is no tool ref, :poop: forgot need to add the following as well as the nuget pkg?

```
<ItemGroup>
    <DotNetCliToolReference Include="BuildBundlerMinifier" Version="2.2.306" />
  </ItemGroup>
```

**Comment by natemcmaster** [comment]
There are two different packages. Correct usage is:
```xml
<PackageReference Include="BuildBundlerMinifier" Version="2.2.306" />
<DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.2.306" />
```

This issue is about BuildBundlerMinifier (package), not BundlerMinifier.Core (command line tool).

**Comment by natemcmaster** [comment]
And to clarify, you should only need one of those. Use command tool if you want to run "dotnet bundle", use package reference if you want it to automatically integrate with the build.

**Comment by spboyer** [comment]
right ok. Making sure I was on the same page.

**Comment by natemcmaster** [comment]
The piece that needs to change is https://github.com/madskristensen/BundlerMinifier/blob/master/src/BundlerMinifier/BundlerMinifier.csproj. It builds a task assembly that is .NET Framework only. To work on both "dotnet-msbuild" and "MSBuild.exe", it should target .NET Standard.

**Comment by spboyer** [comment]
@madskristensen in VS 2017, when I right click and select "Enable bundle on build..." the status bar displays "Unable to install the BuildBundlerMinifier package" 

I have to manually install using the package manager.  Once complete it does not bundle or minify, appears to fail silently.  Not sure if this is related. 

build: VisualStudio 15.0.0-RC.4+26131.1.d15rel

**Comment by madskristensen** [comment]
Ahh, now I see the issue. That command "Enable bundle on build" shouldn't show up on .NET Core projects. It started showing up when the switch to .csproj happened because the project type GUID changed and i'm not filtering on that new GUID. 

"Enable bundle on build" is unsupported for .NET Core and shouldn't be documented

**Comment by simonech** [comment]
@madskristensen how is it going to work for ASP.NET Core projects that use the .csproj already?

**Comment by spboyer** [comment]
@madskristensen  @natemcmaster 
MSBuild integration working within VS 2017, failing on macOS.

```console

/Users/shayneboyer/.nuget/packages/buildbundlerminifier/2.2.306/build/BuildBundlerMinifier.targets(15,5): error MSB4062: The "BundlerMinifier.BundlerBuildTask" task could not be loaded from the
 assembly /Users/shayneboyer/.nuget/packages/buildbundlerminifier/2.2.306/build/../tools/BundlerMinifier.exe. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, C
ulture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/Users/shayneboyer/projects/firstmacapp/firstmacapp.csproj]
/Users/shayneboyer/.nuget/packages/buildbundlerminifier/2.2.306/build/BuildBundlerMinifier.targets(15,5): error MSB4062:  Confirm that the <UsingTask> declaration is correct, that the assembly
and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/Users/shayneboyer/projects/firstmacapp/firstmacapp.csproj]

```

Here is my .targets file

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <PropertyGroup>
        <BuildDependsOn>
            BundleMinify;
            $(BuildDependsOn)
        </BuildDependsOn>
    </PropertyGroup>

    <UsingTask AssemblyFile="..\tools\BundlerMinifier.exe" TaskName="BundlerMinifier.BundlerBuildTask"/>
    <UsingTask AssemblyFile="..\tools\BundlerMinifier.exe" TaskName="BundlerMinifier.BundlerCleanTask"/>

  <Target Name="BundleMinify" Condition="'$(RunBundleMinify)' != 'False'">
    <BundlerMinifier.BundlerBuildTask FileName="$(MSBuildProjectDirectory)\bundleconfig.json" />
  </Target>

  <Target Name="BundleMinifyClean" AfterTargets="CoreClean" Condition="'$(RunBundleMinify)' != 'False'">
    <BundlerMinifier.BundlerCleanTask FileName="$(MSBuildProjectDirectory)\bundleconfig.json" />
  </Target>

</Project>

```

**Comment by natemcmaster** [comment]
Makes sense. 

VS 2017 runs MSBuild on .NET Framework. 
dotnet.exe runs MSBuild on .NET Core.

To fix this issue, BudnelMinifier needs to be cross compiled. This work hasn't been done yet.

Once it has been done, you'll need to choose which assembly to load the task from based on MSBuild's runtime type.

```xml
  <PropertyGroup>
    <_BundlerMinifierTaskAssembly Condition="'$(MSBuildRuntimeType)' == 'Core'">..\tools\netstandard1.6\BundlerMinifier.dll</_BundlerMinifierTaskAssembly>
    <_BundlerMinifierTaskAssembly Condition="'$(MSBuildRuntimeType)' != 'Core'">..\tools\net46\BundlerMinifier.exe</_BundlerMinifierTaskAssembly>
  </PropertyGroup>

  <UsingTask TaskName="BundlerMinifier.BundlerBuildTask" AssemblyFile="$(_BundlerMinifierTaskAssembly)" />
```

**Comment by spboyer** [comment]
Is there an ETA? Need to have consistency for xplat bundling using MSBuild.  Unless we are prescribing that `dotnet-bundle` is the way.

@danroth27

**Comment by danroth27** [comment]
@DamianEdwards
