### ISSUE TITLE
Hash on minifying.

### ISSUE THREAD

**Issue by hardhub** [madskristensen/BundlerMinifier#239]
How to add hash to minified JS file?

I think we need to calculate hash (for example SHA256) for files in bundle. It allows to cache not changed bundle.. and add it to page with url?hash.

Is it possible in current version of bundler minifier?

**Comment by tugberkugurlu** [comment]
this would be nice to have.

**Comment by manigandham** [comment]
If you're using .Net Core MVC then the tag helpers can already do this:

`<script src="/path/to/output/file.js" asp-append-version="true"></script>`

**Comment by hardhub** [comment]
@manigandham 

You are right.. Thanks... It works as expected...
I think I will need to investigate source code for implementation details.
