### ISSUE TITLE
Option to gzip bundles.

### ISSUE THREAD

**Issue by PhonicUK** [madskristensen/BundlerMinifier#24]
Web Essentials 2013 had the option to compress bundles as gzip (.gz) automatically. It'd be nice to see this return.

**Comment by madskristensen** [comment]
Yes, how did I forget

**Comment by madskristensen** [comment]
In the bundleconfig.json file under the `"minify"` object, you can now set the property `"gzip": true`

**Comment by codeMonkeyAndy** [comment]
Hi, getting along great with this extension except for the gzip functionality. Most of my bundles are converted to gzip files that are 10 bytes long when using this tool, however if I use gzip normally to compress the '.min' file it works fine. Are you sure that this feature is working correctly? I'm happy to provided a sample of my problem if required
