### ISSUE TITLE
Stuck on "Task runner explorer running task "Clean output files"..." with 2.4.337

### ISSUE THREAD

**Issue by ericop** [madskristensen/BundlerMinifier#243]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 2.4.337

### Description
On Build, it hangs with message 

> Task runner explorer running task "Clean output files"...

### Steps to recreate
1. Open my Solution in VS2015
2. Ctrl + Shift +B

### Current behavior
With version 2.4.337 it freezes on the build. Last TaskRunner Message is 

> C:\Users\myName\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\hyuz21cg.med\BundlerMinifier.exe clean "C:\src\Solutions\Web Applications\CMich.SearchRegister.Web_MovedToGitlab\bundleconfig.json"

### Expected behavior
With version 2.3.327 it builds fine and outputs the compiled minified js file.

**Comment by ericop** [comment]
Trying to exit VS2015 give the modal message:

> The build must be stopped before the solution can be closed.

**Comment by mgarcos** [comment]
Happening to me too.

**Comment by mgarcos** [comment]
Anyway to install the prior version?

**Comment by ericop** [comment]
I uninstaller the plug in and another older version was there under the covers, I assume from the Web Essentials extension.

**Comment by ericop** [comment]
after I restarted VS2015, that's when I saw a previous version still there.

**Comment by mgarcos** [comment]
I think that happened to me too but I didn't notice that the version was different.  I assumed that it didn't uninstall so I uninstalled that one too.

**Comment by slathrop** [comment]
VC2015 Community now crashes when I load my solution that uses v2.4.

**Comment by vflorean** [comment]
It happens because the file "BundlerMinifier.exe" is not existed in the folder "C:\Users\myName\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\hyuz21cg.med\".

**Comment by Ruikuan** [comment]
VS2017 RC4 crashes when build too, after installed new version BundlerMinifier extension today.

**Comment by ChristineBoersen** [comment]
Since the auto-update we received today, we are having a similar issue. 

I can run the bundlerminifier manually (command line) just fine, but if I let it be part of my normal build process (**or run it manually via task runner explorer**), it crashes visual studio. 

This is happening with multiple projects that have/had been using the extension for nearly a year, and is happening on all workstations that have had the update

Old version 2.3.327
New version 2.4.337

**Comment by illogicz** [comment]
VS simply closes when trying to build now, or I get the message "The build must be stopped before the solution can be closed.", and VS would promptly close after clicking OK. Took me hours to narrow down the cause to this extension.

**Comment by ChristineBoersen** [comment]
Is there a link somewhere to 2.3.327 so I can get my developers working again? This has killed my entire company's ability to work.

**Comment by mgarcos** [comment]
@ChristineBoersen - I was able to restore the old version from a backup of the Visual Studio extension folder.  The folder names in the VS extension folder are cryptic but the contents of the folder will show bundler files.  Remove the current version from the VS extension menu first and close VS.  Then restore the old bundler folder from a backup via windows explorer and reopen VS.  You may have to enable the extension again.

**Comment by ChristineBoersen** [comment]
Yeah only one machine was I lucky enough for that to work, another because of web essentials being installed, re-installed the new version, then uninstalling it hosed the backup copy

**Comment by ChristineBoersen** [comment]
Yes that solved it. Thanks for the quick turn around Mads :)

**Comment by ChristineBoersen** [comment]
However, one at least one machine, I am getting this error when running the bundler/minifier (once you look in task runner's output)
Could not load file or assembly 'NUglify, Version=1.5.4.0, Culture=neutral, PublicKeyToken=15bc7810aec21b5e' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)Process terminated with code 0.

**Comment by ChristineBoersen** [comment]
I think it has to do with you had (if I looked at the commit's earlier correctly) gone to 1.5.5.0 of that library
