### ISSUE TITLE
Minification portion fails with v 2.3.338

### ISSUE THREAD

**Issue by ChristineBoersen** [madskristensen/BundlerMinifier#244]
Since the 2.3.338 version, the bundling portion of the process works as expected, however when it tries the minification portion, this error is produced.

Could not load file or assembly 'NUglify, Version=1.5.4.0, Culture=neutral, PublicKeyToken=15bc7810aec21b5e' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)Process terminated with code 0.

I believe this is just a reference error as I believe you moved to v 1.5.5.0 of that library recently.

**Comment by madskristensen** [comment]
I'm on it. Updated release coming in a few minutes
