### ISSUE TITLE
The tools folder is not included when checked into TFS Source Control

### ISSUE THREAD

**Issue by Bitcosoftware** [madskristensen/BundlerMinifier#253]
### Installed product versions
- Visual Studio: Visual Studio 2017 Pro
- This extension: 2.4.337

### Description
After I download in Visual Studio through the Manage NuGet Packages, it pulls everything down into a packages folder.  Everything is checked in but the tools folder to Visual Studio TFS.  I am not sure if this is by desgin or not, but all my other NuGet Packages check in the DLL's required.  When I upgrade or pull in a new project, it will not refresh the files from the NuGet Package Manager.  I have to physically delete the packages folder manually and refresh everything.

### Steps to recreate
1. Start a Project in VS
2. Use NuGet Package Manger to include Bundler
3. Add to Source Control
4. The tools folder is not included in the TFS source.

### Current behavior
The tools folder is not included in the Source Control

### Expected behavior
The tools folder should be included in the Source Control.

**Comment by madskristensen** [comment]
I would never check in the `packages` folder to source control, but in order to control it in TFS you could use a .tsignore file. I'm closing this issue since it is about source control and not this extension
