### ISSUE TITLE
Make it available for vs2013

### ISSUE THREAD

**Issue by valeriob** [madskristensen/BundlerMinifier#26]
We are currently transitioning from vs 2013 to 2015, and the separation of bundling from webEssential will make our life quite hard because we cannot make it incrementally.

**Comment by madskristensen** [comment]
The Visual Studio APIs used by this extension are not available in VS2013 unfortunately

**Comment by valeriob** [comment]
Is it then possibile to have it back on web essential 2015, maybe off by default, to help transitioning ?

**Comment by madskristensen** [comment]
Why don't you open your solution in VS2015 and make the transition there while the rest of your team is still on VS2013? VS2015 will not try to "upgrade" your projects or anything.
