### ISSUE TITLE
Re-minify all missing!

### ISSUE THREAD

**Issue by DataPrintGrafik** [madskristensen/BundlerMinifier#27]
Hi, in web essentail 2013 there is a menu option "Re-minify all" for minifying all files in project.
This feature is missing in vs2015.
It's VERY IMPORTANT if the javascript files are build from other compilers (ex. TypeScript), or the project is shared with multiple developers because it allow to re minify all before build a release version.

Please put it back!
Thanks

**Comment by madskristensen** [comment]
This is available in version 1.1

**Comment by DataPrintGrafik** [comment]
I'm working with 1.1.56 version and there is no menu for minify all.. where i can found it?
Thanks

**Comment by madskristensen** [comment]
It's on the right-click menu of the solution node and on the bundleconfig.json file. You'll also find it in the top menu under "Build"

**Comment by DataPrintGrafik** [comment]
I have no bundle in my solution, i just need to minify all js files.
Contextual menu not show "minify-all js files" option.
There are some options as:
Update all bundles in solution: i suppose this option is for bundle and not for minify simple js files
Re-compile all files in solution: i suppose this option is not for minify..

what's the option right for minify all js, css and html files?
Thanks

![image2](https://cloud.githubusercontent.com/assets/7148898/9471615/805d46f8-4b51-11e5-9789-ae99e5741098.png)

**Comment by madskristensen** [comment]
Ahh, re-minifying all files that are not part of a bundle is coming. It's not there yet

**Comment by DataPrintGrafik** [comment]
there is a planned release date for reintroduce this feature?
for developers teams with source control is a very important task, actually we have to re-minify all project files manually before publish a release version.
Thanks
