### ISSUE TITLE
Crash on ES6 arrow functions in source files

### ISSUE THREAD

**Issue by irwiss** [madskristensen/BundlerMinifier#277]
### Installed product versions
- Visual Studio: 2017.2 and 2017 Preview
- This extension: 2.4.337

### Description
```
function TestMe() {
    return "test".map(c => 0);
    return "test".map(function (c) { return 0; });
}
```

The first line will cause B&M to crash, the error in the build log is:
`Bundler & Minifier error 0: Stack empty.`

Not sure whether it's 100% reproducible or a little bit less. The code with the arrow function did pass minify once, but that may be a glitch in the matrix or I may be remembering this wrong - I can't make it pass now

**Comment by valeriob** [comment]
Any update on this ? now it's failing the build because of this...

**Comment by Casimodo72** [comment]
@irwiss , @valeriob : This seems to be a NUglify issue (which the BundlerMinifier uses). See https://github.com/xoofx/NUglify/issues/43

**Comment by samjudson** [comment]
@Casimodo72, @valeriob , @irwiss Just coded a fix for issue 43 you mention, but it has made no change to the minified output of the above function. It minifies to the below code successfully in NUglify.

~~~
function TestMe(){return\"test\".map(()=>0)}
~~~

**Comment by rockstardev** [comment]
@samjudson did a great job solving this on NUglify and I've updated referenced NuGets:

https://github.com/madskristensen/BundlerMinifier/commit/c79b3591df57f8419456ced566dd618ff7a3a1ef

That made new nightly you can use to test how this works:

http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/
