### ISSUE TITLE
Set location of `bundleconfig.json` and `compilerconfig.json`

### ISSUE THREAD

**Issue by stanislavromanov** [madskristensen/BundlerMinifier#278]
### Installed product versions
- Visual Studio: 2017 Community
- This extension: 2.4.340

### Description
I would like to know if it would be possible to move the `bundleconfig.json` and `compilerconfig.json` to a separate directory. For example I am moving all configuration files to `Configuration` folder where I keep my application configuration an would also like to keep these files.

Currently it is possible to right-click on `compilerconfig.json` and compile. Then execute `dotnet bundle Configuration\bundleconfig.json`. This is a lot of manual work.

If I move those two files in `/` of the project then everything works automatically whenever I change my files - It compiles them and afterwards bundles them automatically.

### Steps to recreate
1. Create project
2. Move `bundleconfig.json` and `compilerconfig.json` to some other folder than root

### Current behavior
Auto bundling and compilation doesn't work

### Expected behavior
It should work from visual studio automatically.

**Comment by NePheus** [comment]
Same problem here with 2.6.362. Auto-bundling problems, when bundleconfig is in another folder than root-folder. I just can bundle the files by opening the bundleconfig.json and save it, or by manually click "Update Bundles".

**Comment by NePheus** [comment]
Unfortunately the problem is still there. Maybe it is just a small bug in the lib?

**Comment by NePheus** [comment]
@madskristensen I would love to use multiple bundleconfig.json files in different folders, but they are not processed automatically, but just when I open and save them. Is this a bug or a missing feature?

**Comment by Sc0tTyXL** [comment]
> @madskristensen I would love to use multiple bundleconfig.json files in different folders, but they are not processed automatically, but just when I open and save them. Is this a bug or a missing feature?

Is seems that the "multiple bundleconfig.json" is supported as stated in the documentation. Sadly the it doesn't automatically, I've added a separate issue: https://github.com/madskristensen/BundlerMinifier/issues/406

**Comment by Sc0tTyXL** [comment]
@stanislavromanov could you tell me where this was completed. Did you fix it in https://github.com/failwyn/BundlerMinifier ?
