### ISSUE TITLE
Version for package `BundlerMinifier.Core` could not be resolved.

### ISSUE THREAD

**Issue by shravan2x** [madskristensen/BundlerMinifier#284]
### Installed product versions
- Visual Studio: 2017 Community
- This extension: 2.4.337 and 2.2.301, likely all other versions as well

### Description
```
dotnet bundle
Version for package `BundlerMinifier.Core` could not be resolved.
E:\Test\Test.csproj(44,5): Error MSB3073: The command "dotnet bundle" exited with code 1.
```

### Steps to recreate
1. Add the following code to any .csproj file
```
<Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
  <Exec Command="dotnet bundle" />
</Target>

<ItemGroup>
  <DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.4.337" />
</ItemGroup>
```
2. Try to publish

### Current behavior
Throws an error and fails to build. This appears to have started happening only recently. I have used BundlerMinifier successfully in the past.

**Comment by doublnt** [comment]
I have the samw issue with you when I publish to ubuntu 16.0

**Comment by shravan2x** [comment]
Yeah, I removed this package entirely. No one has suggested any fix for almost 2 months now. I will probably use it again if someone provides a fix though.

**Comment by doublnt** [comment]
I solved it in my project.
My environment is` .NET-Core 2.0` and `ubuntu 16.04 -x64` 
my `.csproj` file  contains 

```c#
...
<PackageReference Include="BundlerMinifier.Core" Version="2.4.337" />

 <ItemGroup>
    <DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.4.337" />
  </ItemGroup>

  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="dotnet bundle" />
  </Target>
...
```

when I add `sudo` command, `sudo dotnet publish -c Releasee -o ./publish `
it publish successfully .

**Comment by shravan2x** [comment]
I have not tried `.NET-Core 2.0` yet. I'll check again sometime and post back.

**Comment by doublnt** [comment]
Keep Contact.

**Comment by shravan2x** [comment]
I just tried again on VS2017 15.3 with `.NET-Core 2.0` and version `2.4.337`. It works correctly.

Thank you!

**Comment by LordMike** [comment]
I've just encountered this too. In my case, I had missed `dotnet restore` prior to running `dotnet bundle`. I was refactoring our CI and accidentally moved this before the restore step.

Now. The reason I got this error and not "could not find command" is probably because the build environment contained an older artifact of a previous "dotnet restore" run on another build bot. I've seen other parts of dotnet fail due to the changing paths in the build environment.

**Comment by RillistikPete** [comment]
I'm having this problem now. 
When I try to run 'docker run -it -p 8080:5000 myproject:bec'

```
Version for package `BundlerMinifier.Core` could not be resolved.
```

I've installed latest BundlerMinifier (version 2.8.391), doesn't work still.  I tried reverting back to version 1.1, didn't work either.  I tried deleting, didn't work.  And help??

**Comment by ryanrodemoyer** [comment]
@RillistikPete does your Dockerfile contain a command for `dotnet restore`?
