### ISSUE TITLE
How to add outputs to the publish package?

### ISSUE THREAD

**Issue by Peter-Juhasz** [madskristensen/BundlerMinifier#289]
### Installed product versions
- Visual Studio: 2017 Professional 15.2 26430.16
- This extension: 2.4.340
- Web Compiler extension: 1.11.326

### Description
My project was created from the official ASP.NET Core Web Application template. It is still pretty simple, it has only a single controller with a few views and a LESS stylesheet.

File structure:
 - wwwroot
   - styles
     - site.less
 - Controllers
 - Views
 - bundleconfig.json
 - compilerconfig.json
 - Landing.csproj

compilerconfig.json
```
[
    {
        "inputFile": "wwwroot/styles/site.less",
        "outputFile": "wwwroot/styles/site.css"
    }
]
```

bundleconfig.json
```
[
    {
        "outputFileName": "wwwroot/styles/app.min.css",
        "inputFiles": [
            "wwwroot/styles/site.css"
        ]
    }
]
```

Compilation and bundling/minification is enabled on build, so the required NuGet packages are added to the project:
```
    <PackageReference Include="BuildBundlerMinifier" Version="2.4.337" />
    <PackageReference Include="BuildWebCompiler" Version="1.11.347" />
```

My project is hosted on VSTS, and my build was created from the official ASP.NET Core template. The build process does not use any dotnet CLI steps, but a single Visual Studio Build step to build and publish. I use the "VS2017" Hosted Agent.

But the issue can be reproduced locally. This is the Visual Studio build step using the same parameters:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\msbuild.exe" "C:\a\Landing\Landing.sln" /nologo /nr:false /p:platform="any cpu" /p:configuration="release" /p:VisualStudioVersion="15.0" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="d:\publish\WebApp.zip" /p:DeployIisAppPath="Default Web Site"
```

In the build log I can see the compiler and bundler works as expected:
```
WebCompile:

  WebCompiler: Begin compiling compilerconfig.json
        Compiled wwwroot/styles/site.css
        Minified wwwroot/styles/site.min.css
  WebCompiler: Done compiling compilerconfig.json
BundleMinify:

  Bundler: Begin processing bundleconfig.json
        Minified wwwroot/styles/app.min.css
  Bundler: Done processing bundleconfig.json
```

I also added the contents of wwwroot explicitly to the project:
```
  <ItemGroup>
    <Content Update="wwwroot\**\*;Views\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
```

### Current behavior
I don't find the compiled and minified .css files in the published ZIP package. The only file which is there is site.less, no site.css, no site.min.css and no app.min.css. So this is why I have in the ZIP:

 - wwwroot
   - styles
     - site.less

### Expected behavior
I want to get the output of compiler and minifier published:

 - wwwroot
   - styles
     - app.min.css

**Comment by manigandham** [comment]
That's probably because those files aren't available when the build is running, so they're not picked up. Remove that `<ItemGroup>` and try this `<Target>` instead (directly under the `<Project>` element):

```
  <Target Name="CopyMinifiedFiles" AfterTargets="ComputeFilesToPublish">
    <ItemGroup>
      <DistFiles Include="wwwroot\**" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
```

**Comment by Peter-Juhasz** [comment]
Thank you @manigandham, the workaround works.
