### ISSUE TITLE
How to bundle together files preserving source maps

### ISSUE THREAD

**Issue by valeriob** [madskristensen/BundlerMinifier#293]
### Installed product versions
- Visual Studio: [example 2017 Professional]
- This extension: [example 2.4.353]

### Description
When bundling together more than one file with source map (for example some js generated by typescript), the output bundle only contains source map for the first file bundled.

### Steps to recreate
1) Create a project
2) Add two typescript files
3) Create a bundle with both (enabling source map)
4) Create a web page that references the bundle
5) Run the page with F12 tools and try to debug it

### Current behavior
The browser debugging tool will resolve only the symbols of the last added file to the bundle (the last line with  //# sourceMappingURL= )

### Expected behavior
The browser debugging tool should resolve the symbols of all the file bundled.

**Comment by hg1** [comment]
#112

**Comment by valeriob** [comment]
Cool thanks !
