### ISSUE TITLE
ProcessableScriptTypeList for single minified (not bundled) HTML file

### ISSUE THREAD

**Issue by rudym87** [madskristensen/BundlerMinifier#30]
How can I enable processing of template scripts in a HTML file which is only minified and not included in any bundle?
A workaround which I found is to add an entry in bundleconfig.json with identical inputFiles and outputFile but i don't think this is the proper way to do it.

**Comment by seldary** [comment]
+1

**Comment by madskristensen** [comment]
The latest nightly now adds all minified files to the bundleconfig.json file behind the scenes. So all minified files are processed just like bundles.

**Comment by rudym87** [comment]
I'm trying out the nightly build, but I think it's not working. These are the steps that I'm following:
- initially the project has no bundleconfig.json
- right-clicking an HTML file (e.g. Index.html) gives me the option "Minify file"
- after clicking it, the Index.min.html file is created and nested to the source file, but the source file is now empty (and therefore is the minified version)

This is the content of bundleconfig.json after these steps:
```javascript
[
  {
    "outputFileName": "Index.html",
    "inputFiles": []
  }
]
```
Also, right-clicking again Index.html (which now correctly has also the "Remove from bundling..." entry), and selecting again Minify file, results in another identical entry for Index.html in bundleconfig.json file.
