### ISSUE TITLE
ES6 Arrow Function returning object literal is minified incorrectly

### ISSUE THREAD

**Issue by samjudson** [madskristensen/BundlerMinifier#301]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 15.0.3

### Description
I have a arrow function in a TypeScript file return returns an object literal, which is transposed to an ES6 arrow function correctly. However the minified version of this es6 file causes the arrow function to be converted into an invalid format.

### Steps to recreate
Imagine this arrow function that returns a new object literal:

`var f = n => { return { x : n + 1, y: n - 1 }; };`

In ES6 this function is identical. Once minified however it becomes the following:

`var r=n=>{x:n+1,y:n-1};`

This is no longer a valid arrow function.

The same thing is happening with the ASP.Net Web Optimisation bundler as well.

**Comment by samjudson** [comment]
The following is valid:

`var r=n=>({x:n+1,y:n-1});`

**Comment by samjudson** [comment]
Well my test case is above - doesn't seem to matter what is returned as long as it's an object literal.

If you need more then let me know what you mean?

**Comment by samjudson** [comment]
Interestingly we just had the issue happen again.

Putting var a = 1; into the TypeScript seemed to generate the correct minified file.

~~~~
var f = n => { var a = 1; return { x : n + 1, y: n - 1 }; };
~~~~
Minified down to:
~~~~
var r=n=>{ return {x:n+1,y:n-1}};
~~~~

**Comment by rockstardev** [comment]
Interesting workaround. Until we fix the issue in NUglify I guess we need to notify people they can use this approach. I've saw one issue in NUglify that asks the same thing: https://github.com/xoofx/NUglify/issues/43

**Comment by rockstardev** [comment]
Thanks for the fix @samjudson!

If you can submit PR that updates NUglify (like I did in #348) - let me know and I'll merge it. Would be the best so I don't take the credit.

Otherwise when I have time I'll see to create this update myself and Co-author you on commits.

**Comment by rockstardev** [comment]
OK, merged - new nightly is built, thanks for all your hard work! If there is anything else you want to tackle, let me know.
