### ISSUE TITLE
Expected semicolon or closing curly-brace, found '-'

### ISSUE THREAD

**Issue by davidliang2008** [madskristensen/BundlerMinifier#306]
### Installed product versions
- Visual Studio: [2017 Community 15.4.1]
- This extension: [2.6.362]

### Description
I've been using web compiler to transform .scss files into css files, and the bundler to move and bundle css files into wwwroot directory. 

**Issue 1**: 
I noticed this version of the bundler won't minify the files automatically, like what the previous version 2.5.357 would do, but I think I can do that via settings so I didn't bother to look into this any deeper.

**Issue 2**:
Everything worked fine until I **enable bundle on build**, which downloaded 2 NuGet packages: BuildBundlerMinifier (2.6.362) and BuildWebCompiler (1.11.375).
I got 28 errors. All said `Expected semicolon or closing curly-brace, found '-'` (this might be related to https://github.com/madskristensen/BundlerMinifier/issues/295). And there is a yellow warning sign on BuildBundlerMinifier (as well as BuildWebCompiler) if you pop open Dependencies -> NuGet under the web project.

**Notes:**
I downgraded the BuildBundlerMinifier to 2.5.357 and everything worked perfectly - it generates a minified version of the bundle files, as well as generates bundles on build.

### Steps to recreate
1. File -> New -> Project -> .NET Core to create a ASP.NET Core Web Application
2. Install the latest nodejs 
3. Install Bootstrap beta 2 using npm: `npm install bootstrap@4.0.0-beta.2`
4. Create a theme style file, i.e. dark.scss in a new folder 'assets/styles' and import bootstrap scss: `@import "../../node_modules/bootstrap/scss/bootstrap";`
5. Install Bundler & Minifier and Web Compiler from tools -> extensions and updates
6. Right click on dark.scss -> Web Compiler -> Compile, which should generate `compilerconfig.json` file
7. Add `bundleconfig.json` and output the dark.css file to wwwroot
`[
  {
    "outputFileName": "wwwroot/css/global.css",
    "inputFiles": [
      "assets/styles/dark.css"
    ]
  }
]`
8. Right click on bundleconfig.json, select Bundler & Minifier and check  Enable bundle on build.

**Comment by ChrisASearles** [comment]
Any reason this issue was closed? I'm getting the same problem building Bootstrap 4 beta 2 and downgrading to 2.5.357 didn't work.

**Comment by davidliang2008** [comment]
aww I got everything working together - BuildBundlerMinifier (2.6.362) and BuildWebCompiler (1.11.375) with the latest Visual Studio Community 15.5.2 but I was so busy that I forgot what steps I took to get it working.

Maybe the VS updates fixed it? Have you tried to update to the latest?

**Comment by jgimness** [comment]
@ChrisASearles I have the same setup as you.  Removing the top root and -- color vars allowed the minifier to complete.  There's another issue open to fix this: #218

**Comment by lepipele** [comment]
@davidliang2008 can you re-open this? It's obviously not fixed... anything we can do to help?

**Comment by lepipele** [comment]
OK, I'll likely take care of NUglify error: https://github.com/xoofx/NUglify/issues/17#issuecomment-378685509

Once that's done can we then update this Minifier with new version @davidliang2008? Because it's likely lots of people will run into this problem now that Bootstrap4 uses CSS variables (`--namedColor:#123456` breaks bundling)

**Comment by lepipele** [comment]
Pull request submitted to NUglify: https://github.com/xoofx/NUglify/pull/46

Once they merge can we update dependency and publish new version @davidliang2008 ? @madskristensen ?

**Comment by NicolasDorier** [comment]
This just got merged!

**Comment by NicolasDorier** [comment]
... and nuget pushed :)

**Comment by lepipele** [comment]
@NicolasDorier french connection with @xoofx it seems ;)

@madskristensen can we now get new version of BundlerMinifier? So that everyone can use Bootstrap4?

**Comment by NicolasDorier** [comment]
not even. Now just hoping @madskristensen still use github! Long time since the last activity in this repo. :(

**Comment by lepipele** [comment]
@NicolasDorier well he seems to be commiting last few days. If this issue talk doesn't get his attention I guess we can make use of your Twitter firepower.

**Comment by lepipele** [comment]
2.6.375 out, fixes this problem: https://www.nuget.org/packages/BuildBundlerMinifier/

**Comment by aftab464** [comment]
2.8.xxx version fixed it for me

**Comment by adlesh** [comment]
This may be separate, but this felt like a good place to do put this. If you run into a similar error, for example mine was "Expected semicolon or closing curly-brace, found '@state-text-danger'". Simply remove the @ and wrap the left over in var(--state-text-danger). This allowed me to minify and bundle with no issue.
