### ISSUE TITLE
error MSB3073: The command "dotnet bundle" exited with code 131.

### ISSUE THREAD

**Issue by doublnt** [madskristensen/BundlerMinifier#307]
### Installed product versions
- Visual Studio: [2017 Enterprise Version]
- This extension: [2.4.401]

### Description
When I use Script to publish my Asp.Net Core project on ubuntu Linux. After restore and prepare to publish this project, the error occurs:
 ```c#
  It was not possible to find any compatible framework version
  The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
    - Check application dependencies and target a framework version installed at:
        /
    - Alternatively, install the framework version '1.0.0'.
/src/CNBlogs.Question.Web/CNBlogs.Question.Web.csproj(55,5): error MSB3073: The command "dotnet bundle" exited with code 131.
```

But When I go to my Web folder and use `dotnet publish ` command , it success. I can't figure out why can't use script?

**Comment by digounet** [comment]
same problem here...

`It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /
`

**Comment by EvAlex** [comment]
Faced the same problem after migrating to .NET Core 2.0. Resolved it updating BundlerMinifier cli tool version in .csproj file from 
```xml
<DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.2.301" />
```

to
```xml
<DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.6.362" />
```

**Comment by doublnt** [comment]
```c#
<PackageReference Include="BundlerMinifier.Core" Version="2.6.362" />
```

```c#
<DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.6.362" />
```
Make the version is same can solve this problem.

**Comment by achimismaili** [comment]
> ```cs
> <PackageReference Include="BundlerMinifier.Core" Version="2.6.362" />
> ```
> 
> ```cs
> <DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.6.362" />
> ```
> 
> Make the version is same can solve this problem.

Yes, this solved my problem. Thanks a lot @EvAlex and @doublnt ! 
See also: https://gunnarpeipman.com/aspnet-core-bower-bundle-errors/#comment-230991
