### ISSUE TITLE
Project(s) contained errors...when saving/minifying any .js file

### ISSUE THREAD

**Issue by paultechguy** [madskristensen/BundlerMinifier#317]
I am using the latest bundler/minifier.  When I click save for a JS file, I get an error (see attached).  Even though it says to look in the error list, there are no errors there.  How can I find out was it causing this error on those files I have minify enabled?

It doesn't matter which .js file I compile...they all cause this error.  I can have a simple .js file with "var x = 0;" and saving/minifying will cause this error.  Cleared VS component cache.  Uninstalled and reinstalled this bundle/minify plugin.  Restarted PC.  Nothing has helped.

![error message ](https://user-images.githubusercontent.com/9164881/33792469-9200afae-dc5d-11e7-933a-632de7b92389.jpg)

**Comment by Casimodo72** [comment]
@paultechguy : In the toolbar of Visual Studio's Error List there a combo box where you can choose from to also display such IntelliSense errors. Set this combo box to "Build + IntelliSense". This will make the errors of the BundlerMinifier appear in the Error List.

**Comment by lepipele** [comment]
Thanks for helping @Casimodo72 ;). @paultechguy have you managed to solve this? Tried new version? Wanna know if I can close issue.

**Comment by paultechguy** [comment]
Yes, you can close it.  Although I did try the fix by Casimodo, it didn't work as things were already set to "Build + IntelliSense".  Regardless, I've updated things, including the latest VS typescript, 2.6, and am satisfied I don't see the unclear error message.  I am now on VS 15.6.6 in April of 2018.

Thanks for the ping and helping to keep things fresh.
