### ISSUE TITLE
How to split a Js file with private functions

### ISSUE THREAD

**Issue by ygoe** [madskristensen/BundlerMinifier#321]
This is more of a conceptional question. I'm writing a file that adds a lot of plugins to jQuery. They should be distributed over multiple files. But I've also defined some private functions that should be available to all plugins (files) but not publicly. When minifying the js file, the private functions may get shorter names which is not possible for publicly referenced functions.

Now I could write a number of file like this:

* __start.js: contains the beginning of the scope, `(function ($) { "use strict";`
* __private.js: defines private functions
* _plugin*.js: Adds jQuery plugins
* __end.js: closes the scope, `}(jQuery));`

Then I let all of these files be combined in this order. The problem is that the two half files __start and __end show warnings in the solution explorer because, well, they are invalid on their own.

Is there another solution to splitting up long chunks of JavaScript code in multiple files?

Do I have to try my luck with TypeScript instead?

**Comment by Roamel** [comment]
Hello ygoe,
IMHO, your question is not related to the extension. It would be better to use another site for this, like stackoverflow.com. Nevertheless, from my point of view, you should try ES6 modules with transplier (TypeScript or Babel) or just use RequireJS to write AMD modules. 
Regards Roman
