### ISSUE TITLE
Minify all js files in solution (with no bundle)

### ISSUE THREAD

**Issue by moh-abed** [madskristensen/BundlerMinifier#325]
Is there a way to just keep minifying all js files in solution without having to add bundle entry for each file or folder in bundleconfig.json?

**Comment by lohithgn** [comment]
hi. you can use a globbing pattern. here is what i did to test your scenario:

- in wwwroot/js folder i created a new folder called test
- in test folder, i created a new folder called foo and added a new JS file called foo.js
- in test folder, i created a new folder called bar and added a new JS file called bar.js
- now i created a entry in bundleconfig which looks for wwwroot/js/test folder for any JS file and will bundle it. here is the config entry:
`  {
    "inputFiles": [
      "wwwroot/js/test/**/*.js"
    ],
    "outputFileName": "wwwroot/js/test/test.js"
  }`

hope this helps

**Comment by lepipele** [comment]
Thanks for help @lohithgn

**Comment by lohithgn** [comment]
@lepipele pleasures mine :) glad i could be of help
