### ISSUE TITLE
Vsix extension: BundlerMinifierConsole.exe fails during run

### ISSUE THREAD

**Issue by Roamel** [madskristensen/BundlerMinifier#329]
### Installed product versions
- Visual Studio: 2017 Community v15.5.6 
- This extension: 2.6.368

### Description
Vsix extension is in broken state. Any attempts to do minification of any javascript file produce an error.

### Steps to recreate
1. Install Bundler & Minifier v2.6.368.vsix (http://vsixgallery.com/extensions/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/Bundler%20%26%20Minifier%20v2.6.368.vsix)
2. Try to minify some javascript file using Task Runner Explorer window
3. Error occurs:
```
D:\TestProjects\WebApp1\WebApp1> C:\Users\<User>\AppData\Local\Microsoft\VisualStudio\15.0_937809d8\Extensions\o1311qjs.rli\BundlerMinifierConsole.exe "scripts/issue.min.js" "D:\TestProjects\WebApp1\WebApp1\bundleconfig.json"
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies.
The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at BundlerMinifier.BundleHandler.TryGetBundles(String configFile, IEnumerable`1& bundles)
   at BundlerMinifierConsole.Program.GetConfigFileFromArgs(String[] args, String& configPath)
   at BundlerMinifierConsole.Program.Main(String[] args)
Process terminated with code -532462766.
```
### Current behavior
Extension is in unusable state.

### Expected behavior
Extension produces minified javascript files.

### Workaround
Put Newtonsoft.Json assembly to the folder where extension is installed.
Create BundlerMinifierConsole.exe.config near to BundlerMinifierConsole.exe and specify binding redirects to the Newtonsoft.Json assembly version (in my case it is 10.0.0.0):
```
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by mehdi-mousavi** [comment]
It is happening for v2.6.375, too. I fixed it by copying the NewtonsoftJson assembly v9 to the following folder:

C:\Users\<MyUser>\AppData\Local\Microsoft\VisualStudio\15.0_cfa2c347\Extensions\coo3rrrc.coj

**Comment by jyarbro** [comment]
The config file solution did not work for me, but @mehdi-mousavi had the working solution for me. The path was slightly different though.

**Comment by Roamel** [comment]
Just a note about config: it is needed only in case when NewtonsoftJson assembly has a version that is not the same as required by the extension.

**Comment by Roamel** [comment]
Hello Mads,
build 2.6.377 does not work for my environment (VS2017)
error the same , except that now it requires Newtonsoft.Json, Version=**8.0.0.0**, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed.

**Comment by madskristensen** [comment]
@Roamel please try [latest build](http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/) and see if that does the trick

**Comment by Roamel** [comment]
This build works OK.
Tried to install directly and from VS Extensions and Updates: both are OK.
vsix contains Newtonsoft.JSON assembly v.9.0.1.19813 and it is installed with extension.

**Comment by lepipele** [comment]
Can we close this @Roamel ?

**Comment by Roamel** [comment]
Yes, of course
