### ISSUE TITLE
Installed Nuget extension into VS Community... but nothing appears

### ISSUE THREAD

**Issue by ImTheKeyMaster** [madskristensen/BundlerMinifier#335]
### Installed product versions
- Visual Studio: 2017 Community
- This extension: 2.6.362

### Description
I installed the package and restarted VS.  I do not see a bundleconfig file and not context menu additions when right clicking.  I am running a C# MVC (.NET Framework 4.6.1) web application.  I even wiped out my solution's .vs directory and let Visual Studio rebuild it.  What am I missing?

### Steps to recreate
1. Open "Manage NuGet Packages"
2. select "BuildBundlerMinifier by Mads Kristensen" v2.6.362

### Current behavior
Not seeing any sign of the package running

### Expected behavior
I expected to be able to right click on files and minify them.

**Comment by enginaar** [comment]
+1. I'm seeing an warning icon on BuildBundlerMinifier nuget package.

**Comment by Casimodo72** [comment]
@ImTheKeyMaster : I think you need to install the Visual Studio extension.  Open "Tools" -> "Extensions and updates". Then search for either "Web Essentials 2017" (which also contains the BundlerMinifier) or "Bundler & Minifer" and install one of those extensions. This will add the GUI thingies.

I think the "BuildBundlerMinifier" NuGet package is intended only to be used GUI-less during the build of your solution/project (e.g. on a build server). But I'm not sure.

**Comment by ImTheKeyMaster** [comment]
Okay, so strike this up to having only recently upgraded to VS2017.  It appears bundling, minification andversioning are all baked into Visual Studio now.  My bad.  Just got the the App_Start/BundleConfig.cs working.  Loving life.
