### ISSUE TITLE
How to enable adjustRelativePaths?

### ISSUE THREAD

**Issue by mixerp** [madskristensen/BundlerMinifier#34]
Hi,

The bundled files do not adjust relative paths. Help.

**Comment by Thierry-S** [comment]
As posted in the vs gallery on microsoft.com...

my new bundle screws up the path in css files. The old had adjustRelativePaths=true.

My current Bundleconfig.json looks like this:

    [
      {
        "outputFileName": "style/styles.css",
        "inputFiles": [
          "style/bootstrap/3.2.0/css/bootstrap.css",
          "style/bootstrap-multiselect/0.9.6/bootstrap-multiselect.css",
          "js/jquery-ui/1.10.4/themes/base/jquery-ui.css",
          "js/jquery-ui/1.10.4/themes/base/jquery.ui.resizable.css",
          "images/flaticon/flaticon.css",
          "style/AllStyles.css"
        ],
        "minify": {
          "enabled": true
        },
        "includeInProject": true,
        "sourceMaps": false
      }
    ]

My old output styles.css with Web Essentials 2013 was:

    .ui-progressbar .ui-progressbar-overlay {
	    background: url(../js/jquery-ui/1.10.4/themes/base/images/animated-overlay.gif);

    .ui-widget-overlay {
	    background: #aaaaaa/*{bgColorOverlay}*/ url(../js/jquery-ui/1.10.4/themes/base/images/ui-bg_flat_0_aaaaaa_40x100.png)/*{bgImgUrlOverlay}*/ 50%/*{bgOverlayXPos}*/ 50%/*{bgOverlayYPos}*/ repeat-x/*{bgOverlayRepeat}*/;

    @font-face {
	    font-family: "Flaticon";
	    src: url(../images/flaticon/flaticon.eot);
	    src: url(../images/flaticon/flaticon.eot#iefix) format("embedded-opentype"),
	    url(../images/flaticon/flaticon.woff) format("woff"),


and it is now:

    .ui-progressbar .ui-progressbar-overlay {
	    background: url("images/animated-overlay.gif");

    .ui-widget-overlay {
	    background: #aaaaaa/*{bgColorOverlay}*/ url(images/ui-bg_flat_0_aaaaaa_40x100.png)/*{bgImgUrlOverlay}*/ 50%/*{bgOverlayXPos}*/ 50%/*{bgOverlayYPos}*/ repeat-x/*{bgOverlayRepeat}*/;

    @font-face {
	    font-family: "Flaticon";
	    src: url("flaticon.eot");
	    src: url("flaticon.eot#iefix") format("embedded-opentype"),
	    url("flaticon.woff") format("woff"),


Therefore, my site is effectively broken, no font icons, no jquery UI icons, no bootstrap icons... Look at how the paths have been changed in the bundling process!

**Comment by zecompadre** [comment]
same problem here :(

"adjustRelativePaths : true" ? 

on bundle configuration ?

i've tried and still not working, there was a break compatibility to the old .bundle configurations ?

tks

**Comment by madskristensen** [comment]
Please help test this in the latest nightly build http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/

**Comment by zecompadre** [comment]
Solved 

Option to adjust relative paths. Fixed #34

**Comment by madskristensen** [comment]
Awesome. Thanks for verifying.

**Comment by zecompadre** [comment]
5* :+1:

**Comment by Thierry-S** [comment]
I've tested this too with the nightly build. It's now giving me correct paths in my bundled css. Thanks for the fix!
