### ISSUE TITLE
NullReferenceException when bundleconfig.json is bad

### ISSUE THREAD

**Issue by lukepuplett** [madskristensen/BundlerMinifier#344]
### Installed product versions
- Visual Studio: 2017 
- This extension: NuGet package version 2.6.362

### Description
A NullReferenceException is reported for bad JSON when it should be a friendlier or custom exception type.

### Steps to recreate
1. Assume a good and proper bundleconfig.json with two top-level objects in the top-level array.
2. Add an extraneous comma character between the two objects [ { ... },, { ... } ]
3. Save and build the project.
4. See the error in the Error List pane.

### Current behavior
It's wrong because a null ref making its way to the top of the stack is generally consider a bug, a failure to check or handle and rethrow an more contextual exception.

### Expected behavior
BundleFileProcessor should either check the JSON, break-out the loading and deserializing, and/or expect a null in certain circumstances and throw a BundleConfigFileProcessingException: "Cannot process 'bundleconfig.json'. Check the JSON syntax is formatted correctly and the objects, names and values adhere to the documented specification."

### Stack trace

The "BundlerMinifier.BundlerBuildTask" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BundlerMinifier.BundleFileProcessor.Process(String fileName, IEnumerable`1 bundles)
   at BundlerMinifier.BundlerBuildTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	

blah blah \.nuget\packages\buildbundlerminifier\2.6.362\build\BuildBundlerMinifier.targets

**Comment by rockstardev** [comment]
This should be solved in the latest release thanks to: https://github.com/madskristensen/BundlerMinifier/pull/357

Please test with new version - if problem is still happening feel free to re-open issue. Or if everything now works as expected send some Hooray emoticon ;)
