### ISSUE TITLE
Bundled CSS not Minifying

### ISSUE THREAD

**Issue by sweeperq** [madskristensen/BundlerMinifier#346]
### Installed product versions
- Visual Studio: 2017 Community (15.6.1)
- This extension: 2.5.359

### Description
I'm creating a "Vendors" CSS bundle from node_modules (bootstrap + font-awesome). It correctly creates the vendors.bundle.css file, however, it does not take the additional step of minifying it down to vendors.bundle.min.css like it used to. 

### Steps to recreate
1. Include "node_modules" in project
2. Select the css files to be included in the bundle
3. Right-click and select Bundle & Minifier => Bundle and Minify files...
4. Select a folder and file name
5. Bundled CSS file is properly created, but minified file is missing (It does work for JS)

### Current behavior
It generates the bundled css file in non-minified format, despite having "minify" flag set to true.

### Expected behavior
Should create both the bundled and minified bundled versions of the CSS file, like it does for JS.

**Comment by lepipele** [comment]
Are you using Bootstrap 4? Because if you are, it's bug I'm in process of fixing: https://github.com/madskristensen/BundlerMinifier/issues/306

Just first need NUglify team to update dependency. In the meantime workaround is either to migrate to Gulp or remove variables in `:root` element.

**Comment by sweeperq** [comment]
Confirmed that Bootstrap 4 now properly works with the most current version of Bundler & Minifier. Both the bundle and minified bundle are generated.

**Comment by morphosic** [comment]
Version: 2.6.378
This is still an issue for me. JS works fine for minification. CSS is not working.  The bundled .css file is generated, but not the minified file.

**Comment by lepipele** [comment]
@morphosic check if you have both extension and NuGet DLL referenced in the project. I advise everyone to uninstall extension and just use NuGet DLL - that way solution can bundle on different dev machines.

**Comment by morphosic** [comment]
Ok, I'm using nuget instead of plugin but now I get errors:
![image](https://user-images.githubusercontent.com/1649762/39382674-ec201786-4a2b-11e8-9afa-90e3d1f7a447.png)
This is from a .css file compiled by the Web Compiler plugin.

**Comment by lepipele** [comment]
Err... not CSS expert, but are you @morphosic sure you are allowed class selectors inside of `@-ms-keyframes wiggle`?

Could be bug in WebCompiler (https://github.com/madskristensen/WebCompiler)

Well, anyways glad to hear at least now you get error log on why CSS bundling is not working for you ;)

**Comment by morphosic** [comment]
Perhaps so... It's being built from this:

![image](https://user-images.githubusercontent.com/1649762/39447292-ee546c0c-4c86-11e8-80d2-8fa14ca0ce0e.png)

**Comment by rockstardev** [comment]
Yeah, I see you've logged it on: https://github.com/madskristensen/WebCompiler/issues/370

I'll mention it to @madskristensen when we talk... see if anyone can step up to take over WebCompiler since I definitely don't have time to code that also. If you do end up coding Pull Request and sending it - let me know, I can review and merge.
