### ISSUE TITLE
BundlerMinifier No Longer Overwrites Existing Bundles On File Save

### ISSUE THREAD

**Issue by jwbats** [madskristensen/BundlerMinifier#356]
### Installed product versions
- Visual Studio: 2017 Community
- This extension: 2.6.378

### Description
A few weeks ago, BundlerMinifier stopped automatically generating bundles on js/css file save (maybe it's caused by a VS.NET update?). It works when I manually update my bundles, so I know for a fact my bundleconfig.json is syntactically correct. It also works if I delete my bundles first. Only when there are existing bundles, the extension doesn't work. I've considered the idea that my bundles could be read only files, but I checked this and they are not.

I've disabled almost every other extension to see if there was a conflict. This did not help. I screwed around with settings, causing a bundleconfig.json.bindings file to be produced. Its contents are 'produceoutput=true'. This did not help. I've enabled minification on build. This minifies on build, but not on save. Not helpful when I want to edit js/css in a running project.

The wiki shows a way to call bundling via a CLI command, which requires the Core package. I installed the Core package and tried to call the 'dotnet bundle' command. It does not work: No executable found matching command "dotnet-bundle".

Assigning the 'UpdateBundles' command a keyboard shortcut and then using it, makes it work. But it requires extra keypresses, so it is not ideal. Also, it does not always work, since my VS.NET will tell me that the command is currently not available. Ofcourse, manually updating the bundles via right click on the bundleconfig.json files works perfectly well.

My developer life use to be easy. Now it's a drag. Auto-bundling/minifying is a fantastic feature. But only if it works. I need help getting this fixed, ASAP.

I do not know of any way to debug the source of the problem myself. Are logs of this kept somewhere?

### Steps to recreate
1. Try using BundlerMinifier in a VS.NET 2017 Community .NET Core 2 project.

### Current behavior
Extension does not do its work on file save.

### Expected behavior
Extension does its work on file save.

**Comment by jwbats** [comment]
Found the solution. It was caused by the inclusion of a file that BundlerMinifier wasn't capable of processing.

See my finding here:

https://github.com/xdan/datetimepicker/issues/661

**Comment by jwbats** [comment]
The problem came back just now, despite the fact that I'd fixed it earlier. I had since added another 3rd party library, which could've been the cause. So I commented it out and it started working again. Then I commented it back in, and it kept working.

That was unexpected.

It then occurred to me that my Malwarebytes (Ransomware protection module, to be exact) had been conflicting with my Visual Studio's debugger earlier on (making it slow). I just turned off Malwarebytes and my bundling/minification is working fine.

Let's hope it stays that way now. If I find out more, I will post it here as well.

**Comment by jwbats** [comment]
Thanks for taking action on it. Looking forward to seeing the problem resolved.

**Comment by rockstardev** [comment]
@jwbats - try out new nightly and see if it works better for you: http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/

Look at #351 thread for more details.

**Comment by dotnetshadow** [comment]
@rockstardev  I just tried your latest nightly build on an ASP.NET MVC framework 4.6 package, and I too don't seem to be able to bundle on save. 

I did try the modifying bundleconfig.json added a space managed to get it work after also choosing to Re-Bundle the file. 

Upon Visual Studio 2017 restart same issue, save doesn't work doesn't change the minified file

I'm Running Visual Studio 2017 15.6.7

**Comment by jwbats** [comment]
@rockstardev - At the moment the extension is working well for me. I'm keeping my Malwarebytes Ransomware module disabled and I've refactored my bundleconfig.json file so that large 3rd party libraries, which do not change often, are in their own config section. The refactoring helped to lighten the load and the extension is much more responsive now.

If I run into troubles again, I will try the nightly for sure.

**Comment by rockstardev** [comment]
You are welcome @dotnetshadow ;)

@jwbats if you install new nightly and have problems be sure to check Output Window -> Bundler & Minifier... that will show you details on what is breaking bundling. Or if Malwarebytes Ransomware is locking some file preventing bundling from finishing.

@madskristensen will be publishing this nightly shortly as official release - so I'll close this issue for now, feel free to open new one in case of problems.

**Comment by jwbats** [comment]
@rockstardev - Thanks for your time!

**Comment by madskristensen** [comment]
@rockstardev I just published version 2.7 on the Marketplace. Thanks for all the hard work!!!

**Comment by jwbats** [comment]
I see I've been auto-updated. It's working correctly at the moment. Will let you know if any other problems pop up.
