### ISSUE TITLE
Support recursive directories

### ISSUE THREAD

**Issue by kawazoe** [madskristensen/BundlerMinifier#36]
Hi,

I would really like if you could add support for recursive directories as input files. I was thinking about something simple like this:

```json
"inputFiles": [
      "App/resursiveSearch/*",
      "App/topLevelOnly/"
    ],
```

This would be really useful for our project. I could probably submit a PR if you are interested.

**Comment by bravehartman** [comment]
I want recursive directories too, but I think we should leave the door open for regular expressions.  I see recursive directories as a command argument.  Since nobody in his or her right mind would start a filename with a space (if that's even possible), we could pull off the following syntax.

```
"inputFiles": [
    "App/resursiveSearch/ -r",
    "App/topLevelOnly/",
    "App/libs/*.min.js" // all .min.js files in lib folder (future feature) 
],
```
	
I'm working on a pull request for the recursive piece of this.

**Comment by madskristensen** [comment]
There is now a new property called `recursive` on a bundle JSON object.

**Comment by kawazoe** [comment]
Unless it lets me have some recursive directories and some top level only inside the same bundle, then it doesn't really cover the use case I had in mind.

**Comment by kawazoe** [comment]
@bravehartman Did you had some time to work on that PR? I'm starting to think we should actually support either a plain string or an object with additional properties. Something like this:

```
"inputFiles": [
    { "App/resursiveSearch/", recursive: true },
    "App/topLevelOnly/",
    "App/libs/*.min.js" // all .min.js files in lib folder (future feature) 
],
```

What do you think?

**Comment by madskristensen** [comment]
Check out the latest CI build http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/ 

I just added support for globbing patterns so that you can write something like this:

```json
"inputFiles": [
    "scripts/**/*.js",
    "foo/bar.js",
    "app/*.js"
]
```

**Comment by kawazoe** [comment]
This works really great! For sure, this is a lot better than the recursive property. Since it replaced it in build 76, that also explains why it wouldn't work when I tried it. :+1:

**Comment by madskristensen** [comment]
Yeah, I removed the recursive property again when I added the globbing support
