### ISSUE TITLE
Not working in Visual Studio 2015 Community version

### ISSUE THREAD

**Issue by HansVanderGucht** [madskristensen/BundlerMinifier#37]
Just installed Windows 10 + Visual Studio 2015 Community version.
I installed the extension. 
Not seeing the menu on JS files.

Please HELP

Regards

**Comment by HansVanderGucht** [comment]
It's working.
The thing is. Because this was a old solution ( VS2013  + Web essentials ) .
Solution : Remove the .min.js file under the js files.And then the menu is available

**Comment by datamill2015** [comment]
Mads- Can't get this to run at all. I've installed and uninstalled this 20 times. Normal, admin, you name it. Through Pkg mgr, nuget manager (GUI), nothing... bundleconfig.json never installs. I just can't get it to work. What could I "possibly" be doing wrong? SINCERELY appreciate any direction you could lend. I LOVE your stuff. This problem must be me I guess but I'm lost...! :(
