### ISSUE TITLE
Can't have 'break' outside of loop

### ISSUE THREAD

**Issue by siriu5** [madskristensen/BundlerMinifier#39]
I get the following error during minify:
(Minifier) Can't have 'break' outside of loop: break t
But that is possible in javascript.

Se the following example from http://www.w3schools.com/jsref/jsref_break.asp:
Using the break statement with a label reference, to "jump out" of a JavaScript code block:
var cars = ["BMW", "Volvo", "Saab", "Ford"];
var text = "";
list: {
    text += cars[0] + "<br>"; 
    text += cars[1] + "<br>"; 
    text += cars[2] + "<br>"; 
    break list;
    text += cars[3] + "<br>"; 
}
The result of text will be:
BMW
Volvo
Saab

**Comment by madskristensen** [comment]
Please report the issue on the AjaxMin issue tracker on Codeplex here http://ajaxmin.codeplex.com/
