### ISSUE TITLE
BundleTagHelper is not compatible with ASP.NET Core 2.2 (FileVersionProvider no longer exists)

### ISSUE THREAD

**Issue by HPurvis** [madskristensen/BundlerMinifier#403]
The BundleTagHelper is not compatible with ASP.NET Core 2.2. If the AppendVersion option is enabled, it attempts to create an instance of the FileVersionProvider class. In 2.2, this is now dependency injected as IFileVersionProvider, with the original class no longer existing in that form (see https://github.com/aspnet/Mvc/issues/6371). This causes runtime failures when the tag helper attempts to version the bundles.

To fix the tag helper, it should just be a case of injecting an IFileVersionProvider and using that, however I'm wary of submitting a PR as the change will break compatibility with ASP.NET Core 2.1 and earlier.

For anyone affected by this, a short-term workaround is to turn off the version appending functionality globally. To do this, set up an instance of BundleOptions in your application to be dependency injected into the tag helper so that the default settings are never used, and set AppendVersion to false in that instance (as well as setting the other options appropriately).

**Comment by fishingry** [comment]
In my case, it can produce correct bundle files, but after it, it throw incorrect error.

![2019-03-03_19-15-51](https://user-images.githubusercontent.com/25354610/53704262-2d685f80-3de9-11e9-93b6-a31d88316282.png)

**Comment by fishingry** [comment]
So currently, I install the package, produce bundles, then uninstall it.

**Comment by rockstardev** [comment]
Solved with 2.9.406, @NicolasDorier is the author of fix. 

https://www.nuget.org/packages/BundlerMinifier.TagHelpers/2.9.406

Let me know if you run into any problems with using new version.

**Comment by NicolasDorier** [comment]
A better long term solution is to have a package with both .net 2.1 and .net 2.2 versions where the 2.2 just resolve IFileVersionProvider from the ctor.
