### ISSUE TITLE
Visual Studio 2019 Error

### ISSUE THREAD

**Issue by BobBonser** [madskristensen/BundlerMinifier#420]
### Installed product versions
- Visual Studio: Visual Studio 2019 Enterprise
- This extension: 2.8.396

### Description
Error when saving js file that should be minfied:
System.NullReferenceException: Object reference not set to an instance of an object.
   at BundlerMinifier.BundleFileProcessor.SourceFileChanged(String bundleFile, String sourceFile)
   at BundlerMinifierVsix.BundleService.<>c__DisplayClass11_0.<SourceFileChanged>b__0(Object o) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\BundleService.cs:line 169

### Steps to recreate
1.  Create js file
2. Add file to bundleconfig.json
3. Save file

### Current behavior
No min file is created and no minification is done

### Expected behavior
min file should be created and the js file should be minified.

**Comment by BobBonser** [comment]
Never mind, my stupid error... Missing a comma.

**Comment by vmonatko** [comment]
Microsoft Visual Studio Professional 2019
Version 16.9.4
Bundler & Minifier 2.8.396

Got the error when trying to add bootstrap.js 5.0 to bundle.  Bootstrap 4.6.0 works fine.

**Comment by Shankar8989** [comment]
Same here, got the error when trying to minify the bootstrap.js 5.0. 
When minify is disabled, it works fine with just bundling. Any solution or fixes?
