### ISSUE TITLE
Min Js with SourceMap has extra line.

### ISSUE THREAD

**Issue by aonweb** [madskristensen/BundlerMinifier#43]
Version: 1.1.57
Generated min.js files for both bundles and minified js files with sourcemap have an extra line below the //# sourceMappingURL=somefile.min.js.map. This seem to break source map loading in current version of Chrome (44.0).

**Comment by madskristensen** [comment]
Please help verify this fix in the nightly build version 1.2.68 or newer at http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/
