### ISSUE TITLE
Source Map Files Are Not Generating

### ISSUE THREAD

**Issue by chris-mullins** [madskristensen/BundlerMinifier#44]
I am using Visual Studio Community 2015.  I am not seeing any source map files being generated.  I have tried using 1.2.17, and the nightly build 1.2.73. 

I have tried  with the sourcemaps option set in the config file as well 
[
  {
    "outputFileName": "Scripts/testbundle.js",
    "inputFiles": [
        "Scripts/test.js"
    ],
    "includeInProject": true,
    "sourceMaps": true
  }
]

I am not sure how I can help figure out what is going on.  If there is some kind of log or output I can send you please let me know how to get it and I will add them.

**Comment by rubenmamo** [comment]
I have the same issue as well

**Comment by pranaydutta89** [comment]
:+1:

**Comment by madskristensen** [comment]
I fixed the issue. Also, the JSON property is called `SourceMap` now instead of `SourceMaps`

**Comment by pranaydutta89** [comment]
map file now is only getting created for minified file,not on the simple unminified  bundled file , is this how it work ,or its a bug ??

**Comment by madskristensen** [comment]
That's how it works

**Comment by chris-mullins** [comment]
I can confirm the source map files are now being generated.  Thanks!

**Comment by michaelsogos** [comment]
Hi,
I'm using 1.4.95, i can't figure out how to create source map for a minified js file.

This is my bundleconfig,json
