### ISSUE TITLE
(Bundler & Minifier) Expected ';' in a codebase without semicolons.

### ISSUE THREAD

**Issue by thepra** [madskristensen/BundlerMinifier#440]
### Installed product versions
- Visual Studio: 2019 Community
- This extension: 2.8.396

### Description
Issues with JS sources without semicolons

### Steps to recreate
1. Use ECMAScript 6 or later
2. Have all the code without semicolons

### Current behavior
Complains about missing semicolons:
![immagine](https://user-images.githubusercontent.com/7032509/65413869-bb8e4c80-ddf2-11e9-9e70-e7c67bd82459.png)

### Expected behavior
Semicolons shouldn't matter for minifying.

**Comment by supershowwei** [comment]
to upgrade vsix on http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/
