### ISSUE TITLE
Wrong encoding

### ISSUE THREAD

**Issue by NinjaCross** [madskristensen/BundlerMinifier#45]
Since version 1.2.71 the output file has wrong encoding.
The following image shows the problem.
The row in RED shows the (CORRECT) behaviour of previous version.
The row in GREEN shows the (WRONG) behaviour of current 1.2.71 version.
![encoding](https://cloud.githubusercontent.com/assets/5829421/9663657/c08f4580-5265-11e5-94c5-10a2a5549c31.JPG)

**Comment by madskristensen** [comment]
Can you make the smallest repro possible and paste it here?

**Comment by NinjaCross** [comment]
Repro:
1- Create a new webapplication
2- Create a Typescript file UTF, WITH BOM, and add some chars like "àèéìù"
3- Create a Typescript file UTF, WITHOUT BOM, and add some chars like "àèéìù"
4- Save them: VS2015 generates the JS files
5- Now add these 2 JS files to the bundling.
6- The output of the buindling should be similar to this image, where the FIRST part image is OK, and the LAST part of the image i wrong 
![repro](https://cloud.githubusercontent.com/assets/5829421/9664524/c000d2d2-526a-11e5-8d10-8bbb38f5141c.JPG)

**Comment by madskristensen** [comment]
new build with a fix is available for testing at http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/
