### ISSUE TITLE
purify css

### ISSUE THREAD

**Issue by tinohager** [madskristensen/BundlerMinifier#455]
Hi, have you ever thought about an extension to clean unused css files? Something like this https://purifycss.online/ ?

Tools:
- https://github.com/FullHuman/purgecss
- https://github.com/uncss/uncss

**Comment by madskristensen** [comment]
Yeah, but I don't know how to identify unused CSS. You'd have to run all scenarios of your entire site to figure it out. How would you automate that?

**Comment by tinohager** [comment]
I work a lot with bootstrap i install the library with libman. The problem is i can`t remove some parts without destroy my update compatibility. Maybe a solution was to add some rules to remove selectors from the bundle css. For example remove all selectors `.was-validated`.
