### ISSUE TITLE
Bug on Javascript minifier

### ISSUE THREAD

**Issue by hjd007wwkd** [madskristensen/BundlerMinifier#459]
### Installed product versions
- Visual Studio: Visual Studio Community 2019
- This extension: 3.2.435

### Description
The library can't minify and change the local variable names correctly. I am getting this error message, "Cannot access 'n' before initialization".

### Original Code
Bundleconfig.json
```json
[
  {
    "outputFileName": "wwwroot/js/bundle.min.js",
    "inputFiles": [
      "wwwroot/js/*"
    ]
  }
]
```

Actual code
```javascript
function setupIndexPage() {
    const contentElements = document.getElementsByClassName('content');
    for (const contentElement of contentElements) {
        contentElement.textContent = "Next";
    }
}
```

### Current behavior
The code above is minified as below
```javascript
function setupIndexPage() {
    const n = document.getElementsByClassName("content");
    for (const n of n)
        n.textContent = "Next"
}
```

### Expected behavior
The code has to be minified as similar to below
```javascript
function setupIndexPage() {
    const contentElements = document.getElementsByClassName("content");
    for (const n of contentElements)
        n.textContent = "Next"
}
```

Please let me know if this is a bug or there are any solution for this unexpected behavior.
Thank you

**Comment by uhfath** [comment]
Is there a reason why this is closed? I'm getting same error after minification.
Tested on 3.2.447.
Is there a workaround or a fix somewhere?
