### ISSUE TITLE
Globbing Support?

### ISSUE THREAD

**Issue by dpaquette** [madskristensen/BundlerMinifier#46]
Any chance we could get support for glob patterns when defining inptuFiles? It would be nice if we could add a new file to a folder and not need to update my bundle.

Something along the lines of this:

```
{
    "outputFileName": "dist/all.js",
    "inputFiles": [
      "app/**/*.js"
 ]},
```

**Comment by madskristensen** [comment]
It's on the roadmap

**Comment by madskristensen** [comment]
Can you please help verify that it works by downloading the latest CI build (version 1.2.76 or newer) from there http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/

**Comment by dpaquette** [comment]
Installed the latest and it does seem to be working.

**Comment by apoutney** [comment]
Its not working for me. I have this in my bundleconfig.json

```
{
    "outputFileName": "wwwroot/build/appA.js",
    "inputFiles": [
      "wwwroot/app/appA.js",
      "wwwroot/app/**/*.js"
    ]
}
```

It adds the contents of appA.js but Task Runner Explorer gives me the message saying 'No files matched the pattern wwwroot/app/**/*.js'

I have version 2.2.301 installed.  Any ideas why it cant match any files.  Do I need any other extensions

**Comment by ga1ka** [comment]
This does not work for me, too.

To reproduce: change in bundleconfig.json generated from VS template project in inputFiles fields:
- `"wwwroot/css/site.css"` to `"wwwroot/css/*.css`
- `"wwwroot/js/site.js"` to `"wwwroot/js/*.js"`

Full bundleconfig.json:
```
// Configure bundling and minification for the project.
// More info at https://go.microsoft.com/fwlink/?LinkId=808241
[
  {
    "outputFileName": "wwwroot/css/site.min.css",
    // An array of relative input file paths. Globbing patterns supported
    "inputFiles": [
      "wwwroot/css/*.css"
    ]
  },
  {
    "outputFileName": "wwwroot/js/site.min.js",
    "inputFiles": [
      "wwwroot/js/*.js"
    ],
    // Optionally specify minification options
    "minify": {
      "enabled": true,
      "renameLocals": true
    },
    // Optinally generate .map file
    "sourceMap": false
  }
]
```
I was using:
- "BundlerMinifier.Core": "2.0.238" with .net core 1.0 and asp.net core 1.0.*
- "BundlerMinifier.Core": "2.2.306" with .net core 1.0 and asp.net core 1.0.*
- "BundlerMinifier.Core": "2.2.306" with .net core 1.1 and asp.net core 1.1

But every time i got warning: "No files matched the pattern".
