### ISSUE TITLE
Browsers don't support minified @supports-or

### ISSUE THREAD

**Issue by AbbasBHF** [madskristensen/BundlerMinifier#469]
### Installed product versions
- Visual Studio: 2019 Enterprise 16.4.0
- Google Chrome 80.0.3987.106
- Mozilla Firefox 72.0.2
- This extension: 2.8.396

### Description
This extension minify
`@supports ((position:-webkit-sticky) or (position:sticky))`
to
`@supports ((position:-webkit-sticky)or(position:sticky))`
But browsers (I just tested on Chrome and Firefox) don't support this.

**Comment by markhobson** [comment]
NUglify performs the minification and looks like this issue https://github.com/xoofx/NUglify/issues/58 has been fixed in 1.5.14. Can we bump the dependency to this fix?
