### ISSUE TITLE
There was a error minifying 

### ISSUE THREAD

**Issue by attiqeurrehman** [madskristensen/BundlerMinifier#47]
Hi,

I am trying to bundle and minify css and javascript files, javascript files bundle and minified perfectly fine but it's not the case with css, when I save **bundleconfig.json** it gives me the following error:

> There was a error minifying custom.css

**Comment by madskristensen** [comment]
That's usually because there is a syntax error in the css file. Can you share the file?

**Comment by attiqeurrehman** [comment]
Sure here's the file.

-A


On Tue, Sep 8, 2015 at 6:44 PM, Mads Kristensen <notifications@github.com>
wrote:

> That's usually because there is a syntax error in the css file. Can you
> share the file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madskristensen/BundlerMinifier/issues/47#issuecomment-138563390>
> .
>



-- 
Attiqe Ur Rehman

**Comment by madskristensen** [comment]
Please share it here, it doesn't work when attached to the github email

**Comment by attiqeurrehman** [comment]
http://1drv.ms/1LhB4IO

**Comment by madskristensen** [comment]
That minifies just fine for me. No problems whatsoever. Can you please try the latest CI build from there http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/ and see if that fixes the issue?

**Comment by madskristensen** [comment]
It may be an encoding issue. Can you send the actual file to madsk at Microsoft com?

**Comment by madskristensen** [comment]
It may be an encoding issue. Can you send the actual file to post at madskristensen net?

**Comment by attiqeurrehman** [comment]
I have tried with latest build from the link you shared but still same error. Do you want me to post css file at [madskristensen.net](http://madskristensen.net/)?

**Comment by madskristensen** [comment]
Please send it to `post at madskristensen net`
