### ISSUE TITLE
Improvement in the project update process

### ISSUE THREAD

**Issue by kawazoe** [madskristensen/BundlerMinifier#48]
In the current version, when you update the nuget package, you completely rewrite the Error and Import condition attribute. This causes a problem for us who want to only generate the bundles in specific configurations. For instance, if I want to generate the bundles only in release build, I would have to use this code:

```
<Import Project="..\packages\BuildBundlerMinifier.1.2.77\build\BuildBundlerMinifier.targets" Condition="Exists('..\packages\BuildBundlerMinifier.1.2.77\build\BuildBundlerMinifier.targets') And '$(Configuration)' == 'Release' " />
```

Notice the additional condition at the end. It would be great if you could detect those customization and keep them in place after an update.

**Comment by madskristensen** [comment]
I don't control that from the extension currently. NuGet is handling that automatically for me. I'm not sure if I can do anything, except introduce a new conditional property that you can set. Let me try that

**Comment by madskristensen** [comment]
I've added a conditional property in the NuGet package that you can set from your .csproj file.

You can set it to `false` with a condition like this:

```xml
<RunBundleMinify condition="'$(Configuration)' != 'Release'">false</RunBundleMinify>
```

Please help verify that it work by upgrading the NuGet package to the latest version (1.3.93 or later)

**Comment by kawazoe** [comment]
This is a brilliant solution and it works as expected. I only had to tweak the string a little for it to work as it wouldn't recognize the condition for some reason. This is the exact string that I added to the PropertyGroup:

```xml
<RunBundleMinify Condition=" '$(Configuration)' != 'Release' ">False</RunBundleMinify>
```

Thanks!
