### ISSUE TITLE
Occur ReferenceError: Cannot access 'variable' before initialization when minify 'for (const x of y) { }'.

### ISSUE THREAD

**Issue by supershowwei** [madskristensen/BundlerMinifier#499]
### Installed product versions
- Visual Studio: 2019 Enterprise
- This extension: 3.2.449

### Description
Occur ReferenceError: Cannot access 'variable' before initialization when minify 'for (const x of y) { }'.

### Steps to recreate
1. Sample code:

```js
function test(arr) {
    for (const abc of arr) {
        console.log(abc);
    }
}

test([1, 2, 3, 4]);
```

And the minified result:

```js
function test(n){for(const n of n)console.log(n)}test([1,2,3,4]);
```

2. Then occur ReferenceError: Cannot access 'n' before initialization.

### Current behavior
'for (const x of y) { }' is legal syntax what iterate item of y. The wrong minified result 'for(const n of n)' that using same variable name on collection and item.

### Expected behavior
I't will be ran success.

**Comment by supershowwei** [comment]
need to upgrade NUglify to 1.6.4

**Comment by supershowwei** [comment]
Fixed on v3.2.451

**Comment by hufsa** [comment]
When will this be released?

**Comment by supershowwei** [comment]
You can download the newest versions at the [nightly build](http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/).

**Comment by hufsa** [comment]
Is there a nightly build for the nuget package (for CI scenarios)?
