### ISSUE TITLE
Enable automatic minification

### ISSUE THREAD

**Issue by scottdorman** [madskristensen/BundlerMinifier#5]
Once a file has been minified, when changes to the source file are saved the .min (and corresponding .map file, see #4) should automatically be updated. This would be consistent with the behavior of earlier versions of Web Essentials.

**Comment by madskristensen** [comment]
Hmm, this should already work

**Comment by scottdorman** [comment]
I see what the issue is. This *does* work when the source file is saved from within Visual Studio. In my case, I'm using a grunt task to generate the .css file from a .less file, so even though the .css file is updated the BundlerMinifier extension isn't seeing the source file change (since it's effectively an external process that's saving the file) and isn't performing the automatic minification. If I subsequently open the .css file and save it from with Visual Studio, the .min.css file gets updated appropriately. I think it boils down to the interaction between using grunt/gulp to compile the .less file and the listener in the minifier. Since it's not actually Visual Studio doing the saving of the source file in this case, the listener isn't being notified that anything happened to the source document.

**Comment by madskristensen** [comment]
You typically won't use both Grunt/Gulp and this extension. Either use Gulp for compiling LESS and minifying (which is built in to the LESS compiler) or use this extension

**Comment by scottdorman** [comment]
I want both a minified and non-minified version created and I couldn't see how to do that properly within the grunt task. What I have right now is a grunt task which does the LESS compilation into an unmified CSS file and then this extension to minify the CSS. If I can get the grunt task (or figure out how to move it to using gulp instead) to give me both files (and the sourcemap) then I'd be all set.

**Comment by madskristensen** [comment]
Gulp can do all that
