### ISSUE TITLE
Error in minified .js file

### ISSUE THREAD

**Issue by sdshankins** [madskristensen/BundlerMinifier#50]
After minifying a javascript file, concatenating several *.min.js files together and referencing the new concatenated javascript file, I receive a script error on the web page (primarily using IE, differs depending on the browser, but consistently errors).  Referencing the minified stand-alone files individually on the webpage does not produce an error however.  I believe I have traced the problem to the fact that the minified file drops the final semicolon, even when present in the original un-minified file.  Adding the semicolon to the minified file and reconcatenating fixes the error.

You can recreate this issue by getting, for example, the Bootstrap NuGet package and choosing to minify the bootstrap.js file (with or without modifications).  The original bootstrap.min.js file contains the closing semicolon, but after running "Minify File" it will not.

I have installed version 1.2.77 as mentioned in #47 but with the same results.

**Comment by madskristensen** [comment]
Have you tried setting the `termSemicolon` property to either true or false?

```json
"minify": {
  "enabled": true,
  "termSemicolons": true
}
```

**Comment by sdshankins** [comment]
Adding that to the project's bundleconfig.json adds the terminating semicolon to the min file correctly when saving the original script file.  Thanks for the info.  

Is there any configuration I can change in order to have that setting injected by default when the bundleconfig.json file is first created in the project?  I found the bundleconfig-schema.json file but didn't know where the proper setting should be placed or even if that would be the targeted file.

**Comment by madskristensen** [comment]
Did you set it to true? I'll change the default since it appears that it was not the correct value
