### ISSUE TITLE
Azure Devops CI 'build' task successfully runs bundling but no '.min' files in Artifacts

### ISSUE THREAD

**Issue by Tomboi88** [madskristensen/BundlerMinifier#518]
### Installed product versions
- Visual Studio: Enterprise 2019 _(Version 16.6.2)_
- JetBrains Rider: 2020.1.4 _(Build #RD-201.8538.1)_
- This extension: 3.2.449
- .NET Version:  .NET CORE 3.1

### Description
Azure Devops, the build pipeline runs without errors but no '.min' files are produced within the Artifacts.

The issue has been identified when the naming convention has changed to include a _period_ within the file names.

`
  Bundler: Begin processing bundleconfig.json  
  	Minified wwwroot/js/SiteScripts/siteScripts.min.js  
  	Minified wwwroot/js/AccountManagement/WebUser/webUser.min.js  
  	Minified wwwroot/js/CRM/Department/department.min.js  
  	Minified wwwroot/js/CRM/Institution/institution.min.js  
  	Minified wwwroot/js/PatientManagement/Patient/patient.min.js  
  	Minified wwwroot/js/PatientManagement/TreatmentType/treatmentType.min.js  
  	Minified wwwroot/js/Utils/utils.min.js  
  	Minified wwwroot/css/SiteStyles/siteStyles.min.css  
  Bundler: Done processing bundleconfig.json
`

### Working Version
Working Platforms:
- VisualStudio and Rider IDE's
- Azure Devops

When the input files .js and .css files are named:
- wwwroot/js/SiteScripts/siteScripts.js
- wwwroot/css/SiteStyles/siteStyles.css

### Issue Identified
Working Platforms:
- VisualStudio and Rider IDE's

Locally within both IDE's the Bundle and Minification process with this naming convention works as expected.

When the input files .js and .css files are named:
- wwwroot/js/SiteScripts/site.Scripts.js
- wwwroot/css/SiteStyles/site.Styles.css

**Comment by Tomboi88** [comment]
I can confirm that this issue has been resolved.

steps:
- Setup a new Pipeline using ASP.NET Core (.NET Framework) template
- Running the build using the windows-2019 agent.

![image](https://user-images.githubusercontent.com/4938651/98386190-caac7a00-2047-11eb-9772-d83e2ccf7a38.png)

**Comment by RichClaussen** [comment]
Is this a renewed issue? I'm seeing in my build pipeline:
![image](https://user-images.githubusercontent.com/1966049/201838075-7529bcc9-3caf-42e2-9da9-1dfa00fac59a.png)
However, the `.min.css` is not in the resulting artifact.

**Comment by JTraill** [comment]
I am also experiencing this issue

**Comment by JTraill** [comment]
Issue still persists for me
