### ISSUE TITLE
Don't Bundle Output Files When Globbling

### ISSUE THREAD

**Issue by bravehartman** [madskristensen/BundlerMinifier#52]
When the output files are included in an input pattern, the output files from the previous bundle.js/bundle.min.js are included in the new bundle.js/bundle.min.js.  This causes duplication and the file size keeps increasing.  The output files should either be deleted before bundling or ignored while bundling.

Here is a failing unit test that reproduces the issue based on an existing unit test.

```
        [TestMethod]
        public void DontBundleOutputFile() {
            _processor.Process("../../artifacts/globbingSubFolders.json");
            _processor.Process("../../artifacts/globbingSubFolders.json");

            string out2 = File.ReadAllText(new FileInfo("../../artifacts/globbing/out2.js").FullName);
            Assert.AreEqual(out2, "var a = 1;\r\nvar b = 2;");

            string out2Min = File.ReadAllText(new FileInfo("../../artifacts/globbing/out2.min.js").FullName);
            Assert.AreEqual(out2Min, "var a=1,b=2");
        }
```

**Comment by madskristensen** [comment]
Thanks, the unit test was very helpful. Great bug report!!!
