### ISSUE TITLE
CSS bundling doesn't work under a virtual directory

### ISSUE THREAD

**Issue by mariannk** [madskristensen/BundlerMinifier#525]
### Installed product versions
- Visual Studio: 16.8.0
- This extension: 3.2.449

### Description
CSS bundling doesn't work under a virtual directory, coz the BundlerMinifier library does not take into account the application path when transforming relative links

**Comment by AndreiMaz** [comment]
@madskristensen Any updated on this?

**Comment by AndreiMaz** [comment]
@madskristensen will you accept pull request for this issue?

**Comment by madskristensen** [comment]
@AndreiMaz absolutely
