### ISSUE TITLE
Provide Ignore Files Pattern

### ISSUE THREAD

**Issue by bravehartman** [madskristensen/BundlerMinifier#54]
I would like to be able to include all .js files in a folder except for test/spec files.  It would be nice to have a way to ignore *spec.js or other types of files from the bundle.

Something like this would be great:
```
{
    "outputFileName": "scripts/bundle.js",
    "inputFiles": [
      "scripts/**/*.js"
    ],
    "ignoreFiles":[
      "*spec.js",
      "*.test.js"
    ],
    "minify": {
      "enabled": true
    },
    "sourceMaps": true
}
```

**Comment by madskristensen** [comment]
You can now do this:

```json
"inputFiles": [
      "scripts/**/*.js"
      "!*spec.js"
 ]
```

Any input file pattern starting with an exclamation mark will be ignored.

Please help test this in the latest CI build http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/
