### ISSUE TITLE
Error minifying on v3.2.465

### ISSUE THREAD

**Issue by Gruski** [madskristensen/BundlerMinifier#543]
Could not load file or assembly 'NUglify, Version=1.13.6.0, Culture=neutral, PublicKeyToken=15bc7810aec21b5e' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Process terminated with code 0.

**Comment by aderrose** [comment]
@Gruski You may have seen already but @iamr8 has found a manual workaround for this issue. [Issue 542](https://github.com/madskristensen/BundlerMinifier/issues/542#issuecomment-796088366)

**Comment by Gruski** [comment]
OK, got it working but shouldn't the package installer install the correct version of Nuglify.dll. Also doesn't support latest version of Nuglify.dll v1.13.8. v1.13.6 still fails to minify script as mentioned here. https://github.com/madskristensen/BundlerMinifier/issues/537

**Comment by aderrose** [comment]
Without looking into the code I suspect that there is an incorrect package reference so NuGet is doing what it's told.  I'm fairly new to GitHub but it should be possible to find the reference and "push" a correction to the project.

With regard to version 1.13.8 not working, again I suspect that 1.13.6 is being requested specifically somewhere but the package reference is saying to include 1.9.1, hence the problems.

**Comment by Gruski** [comment]
I am new to GitHub too. I was hoping who ever does the nightly builds can fix this in the next one.

**Comment by aderrose** [comment]
I've downloaded the code and found the references to Nuglify which seems to be the easy part :) I'm struggling to get one project to build so I'm not sure if what I've changed actually works.

**Comment by aderrose** [comment]
Hi @Gruski, I had a look at the code and bumped NUglify to the latest v1.13.8.  Mads has merged my pull request which has already been built into v3.2.467.  I've just downloaded it and tried it out and all seems well.  If you haven't already [download the latest](https://www.vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/) and see how you get on.

**Comment by Gruski** [comment]
@aderrose Yes, thank you, I noticed that yesterday and installed it. Works great for me so far.
