### ISSUE TITLE
How do I bundle files from a Razor Class Library or Shared Project?

### ISSUE THREAD

**Issue by craigpath** [madskristensen/BundlerMinifier#549]
### Installed product versions

- Visual Studio: 2019 Professional
- This extension: 3.2.449

### Description

I'm new to .NET Core and cannot, for the life of me, figure out how to get a JavaScript file from a Razor Class Library into my bundle. I've Googled and read tons of articles and StackOverflow posts and I'm so incredibly confused, any help would be much appreciated...

I have a .NET 5.0 web project, a .NET CORE 3.1 Razor Class Library, and a Shared Project... And there seem to be _lots_ of ways to reference JS files in the web project that live in either of the other two, but I can only get them to work directly from `<script>` tags... The only way I've been able to get them into my bundle is by using a relative path like `"../SharedProject/wwwroot/js/file.js"`... Which I assume will _not_ work whenever I try to deploy my website?

Thanks in advance -- This is driving me _crazy_!!

**Comment by jweschenfelder** [comment]
Hi @craigpath, 
is this a real bug/issue with BundlerMinifier or just a question about how to use Blazor? If it is just a question about how to use Blazor or BundlerMinifier, I would think that StackOverflow would be the better choice to ask a question. Usually, GitHub is ONLY(!) used to report bugs or if you request new features which BundlerMinifier does not support yet. We had used CSS in a Blazor WebAssembly project where the CSS file was taken from a shared project below the server project. And usually it should work in the way: https://blazor-university.com/component-libraries/ or https://stackoverflow.com/questions/60533748/how-to-reference-js-css-files-from-other-blazor-library-than-itself by referencing the JS as follows: <script src="_content/*assembly_name*/wwwroot/js/file.js"></script>. And this should also work after publishing/deploying the Blazor project. We had rather the issue that BundlerMinifier stopped to work after a recent Visual Studio update as mentioned here: https://github.com/madskristensen/BundlerMinifier/issues/536
