### ISSUE TITLE
Important comments not preserved n JS files

### ISSUE THREAD

**Issue by LarterStyles** [madskristensen/BundlerMinifier#56]
Important comments are not preserved in minified scripts, e.g.:

```javascript
//! This comment gets nuked
```

Interestingly however, important comments are maintained in minified stylesheets, e.g.:

```css
/*! This comment gets kept */
```

The bundleconfig.json file is using the default settings in both cases:

```javascript
  {
    "outputFileName": "Scripts/Foo.js",
    "inputFiles": [
      "Scripts/Foo.js"
    ]
  },
  {
    "outputFileName": "Styles/Bar.css",
    "inputFiles": [
      "Styles/Bar.css"
    ]
  }
```

**Comment by LarterStyles** [comment]
Just noticed that HTML comments aren't stripped at all.

**Comment by madskristensen** [comment]
You can control that in the minification option in the bundleconfig.json file

```json
"minify": {
	"enabled": true,
	"preserveImportantComments": true
}
```

**Comment by LarterStyles** [comment]
How would I set these as "global defaults"? (i.e. so that all minified files all inherit these settings automatically)

There's definitely some variation in how comments are handled by default (e.g. important JS comments are stripped, CSS aren't, whereas all HTML comments are left in tact) -- might  I suggest that we implement some consistency here.

**Comment by madskristensen** [comment]
Good point. Consistency is good. I'd suggest that `preserveImportantComments` should be set to `false` by default

**Comment by madskristensen** [comment]
Actually, I think important comments should be preserved by default

**Comment by LarterStyles** [comment]
Agreed -- they've obviously been deemed significant, so it seems ruthless to discard them.
