### ISSUE TITLE
How to force the *dotnet CLI tool* (**dotnet bundle**) to use the latest *NUglify* version

### ISSUE THREAD

**Issue by rpgkaiser** [madskristensen/BundlerMinifier#568]
### Installed product versions
- Visual Studio: 2019 Community (16.11.0)
- This extension: 3.2.449

### Description
The *minifier* is failing to minify JavaScript code with blocks containing a single statement, corresponding to a **const** declaration, like
`if (a) { 
  const b = f2.foo( { } ); 
}`
Using the latest version of the *NUglify* library, this issue doesn't happen.
So, is there any way to force the *dotnet bundle* tool to use the latest version of *NUglify*?

Thanks.

**Comment by rpgkaiser** [comment]
Never mind. What we really need is to update to the latest NUglify, like issue [#596](https://github.com/madskristensen/BundlerMinifier/issues/569#issue-973512459) suggest.

**Comment by Gruski** [comment]
Over a year later and still no update to latest Nuglify. How did you solve your issue?

**Comment by rpgkaiser** [comment]
I just dropped this and used gulp instead.
