### ISSUE TITLE
Source Map Files are not being loaded in Chrome

### ISSUE THREAD

**Issue by chris-mullins** [madskristensen/BundlerMinifier#58]
Source Map Files are not being Loaded in Chrome (45.0.2454.85)
I am using version 1.2.80

The map files load in Firefox and IE just fine, but they do not load in Chrome.  There are no errors reported in the Chrome console.  

I generated minified files with sourcemaps using uglifyjs for the same files to make sure that my Chrome browser was not to blame, and those map files worked correctly.

**Comment by madskristensen** [comment]
Please open a bug on the AjaxMin repo here http://ajaxmin.codeplex.com/
