### ISSUE TITLE
Enable bundleconfig.json is disabled

### ISSUE THREAD

**Issue by danicomas** [madskristensen/BundlerMinifier#59]
What is happening @madskristensen ?

![image](https://cloud.githubusercontent.com/assets/4038192/10016688/286f2b26-6129-11e5-87f5-a64b493a2339.png)

Version:
1.3.87

**Comment by danicomas** [comment]
How Can I enabled this or exist some manual process to do it?

**Comment by danicomas** [comment]
https://github.com/madskristensen/BundlerMinifier/blob/672d786c9a2b53f93cf757e5ff7ef435fa9500a5/src/BundlerMinifierVsix/Commands/BundleOnBuild.cs#L53 ?¿?

**Comment by danicomas** [comment]
@madskristensen Can we add the same call that you used in VS 213 to runOnBuil?

**Comment by madskristensen** [comment]
It isn't enabled for website projects because it requires MSBuild and that's not available for website projects. However, when Task Runner Explorer integration comes online, it can be done with that.

**Comment by danicomas** [comment]
@madskristensen Could you let me know how you did in the last version VS Web Essential 2013? I would like to implement this functionallity to work with this kind of projects. Regards

**Comment by danicomas** [comment]
How you did it without MSBuild? @madskristensen

**Comment by madskristensen** [comment]
I did it by listening to the build event in Visual Studio. You can use `Shift+Alt+I` to re-build all bundles as a workaround

**Comment by danicomas** [comment]
To add a listening is not so difficult. Isn't it or is it difficult in this new version? @madskristensen

**Comment by madskristensen** [comment]
It wouldn't be difficult at all in this new version. I just haven't gotten around to implementing it yet. Doing it through Task Runner Explorer is the best way to do it though, instead of listening to the build event

**Comment by danicomas** [comment]
Are you saying that after the Task Runner Explorer update it will be available? Do you know when it will be available?

**Comment by madskristensen** [comment]
Yeah, I should be able to add that today

**Comment by danicomas** [comment]
Oh well thanks @madskristensen :D

**Comment by danicomas** [comment]
One question @madskristensen. Your update will be in this project or depends on other extension or VS update?

**Comment by madskristensen** [comment]
This project only

**Comment by danicomas** [comment]
Nice @madskristensen

**Comment by madskristensen** [comment]
Try this latest CI build http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/

Open the Task Runner Explorer window by right-clicking the `bundleconfig.json` and selecting "Task Runner Explorer". Then bind the `All Files` to the `After Build` event.

**Comment by danicomas** [comment]
Awsome @madskristensen it works perfectly. Thanks so much for your quick answer.
