### ISSUE TITLE
javascript map files not generated

### ISSUE THREAD

**Issue by brunis** [madskristensen/BundlerMinifier#61]
Hi,

Docs arent ambigious on .map file generation, but it doesn't happen "automagically" .. maybe a setting in bundleconfig.json?

And turn it on by default?

regards,
Dennis

**Comment by stewartadam** [comment]
+1, I can't figure out how to control sourcemap generation. I have them excluded form my source control so they're in the project but missing on the disk, and minifying the source files isn't regenerating them.

**Comment by stewartadam** [comment]
So after browsing through other tickets, I found #64 which showed a ```"sourceMap": true``` line for the JS files in the ```bundleconfig.json``` file. After adding this line, source maps were generated as expected.

It would be nice to note this in the documentation & homepage.
