### ISSUE TITLE
Running from CI server

### ISSUE THREAD

**Issue by kirk-marple** [madskristensen/BundlerMinifier#62]
I'm trying to use the BundlerMinifier from our continuous integration server (Appveyor), rather than in VS IDE, but it seems like the Task Runner operations never get executed.

Are there any suggestions on how to do this manually via script, or what package to add to my package.json to make this happen on the CI server?

Thanks,
Kirk

**Comment by madskristensen** [comment]
Task Runner Explorer is a VS only thing. You need to right-click the `bundleconfig.json` file and hit **Enable bundling on build...**. That will install a NuGet package that will add an MSBuild task so it can work on a CI server. This doesn't work on Website projects or ASP.NET 5 projects.

**Comment by kirk-marple** [comment]
I am using this in ASP.net 5 actually. Do you mind telling me which package
gets added so we can do it manually?

**Comment by madskristensen** [comment]
It's the **BuildWebCompiler** NuGet package. However, I don't know how to hook it up to the .xproj to run the .targets file inside that package from an ASP.NET 5 project
