### ISSUE TITLE
Minified JS file + sourcemap not updated automatically on save

### ISSUE THREAD

**Issue by LarterStyles** [madskristensen/BundlerMinifier#64]
My **bundleconfig.json** file looks like this:

```javascript
[
    {
        "outputFileName": "Scripts/Foo.Bar.AppScriptParts.MarketUpdate.js",
        "inputFiles": [
            "Scripts/Foo.Bar.AppScriptParts.MarketUpdate.js"
        ],
        "sourceMap": true
    },
    {
        "outputFileName": "Styles/Foo.Bar.AppScriptParts.MarketUpdate.css",
        "inputFiles": [
            "Styles/Foo.Bar.AppScriptParts.MarketUpdate.css"
        ]
    },
    {
        "outputFileName": "WebPart/Foo.Bar.AppScriptParts.MarketUpdate.html",
        "inputFiles": [
            "WebPart/Foo.Bar.AppScriptParts.MarketUpdate.html"
        ]
    }
]
```

Both the HTML and CSS files are re-minified automatically when they're updated / saved, however the JS file isn't. The file paths are all definitely correct, because if I manually update / save **bundleconfig.json** instead, then all three minified files are generated successfully.

**Comment by cjmagee** [comment]
I wasn't able to repeat this, even recreating the same project structure and config file you had.

Is the JS file being saved inside Visual Studio, or from an external program?

**Comment by madskristensen** [comment]
I can't repro it either

**Comment by mattfraley1** [comment]
I ran into this issue as well. I wondered if it might be conflicting with another plugin. Just about the only other non Mads add in I had installed was CodeRush for Roslyn (Preview).  I disabled it, and BundlerMinifier started automatically bundling on file save.  The kicker is that I re-enabled CodeRush and BundlerMinifier is still working.  So I don't know if this will help, but thought I would mention it.

**Comment by LarterStyles** [comment]
This appears to be intermittent... When I originally logged this issue, I'd already tried closing + reopening VS + rebooting my PC to no avail, so it certainly wasn't a one-time-freak-thing. However, these same files are now minifying correctly (I haven't installed / uninstalled any other extensions in that time so not sure what's to blame).

I'm happy for you guys to close this one if you like, and I'll reopen if I can repro again.

**Comment by sambruggeman** [comment]
Experiencing the exact same thing, in 2013 the files are updated without any problems, when switching to 2015  with the new bundler and minifier extension it just doesn't update the file anymore. And even better; when I remove the min file and RMB > minify the source file it also creates minified files for 5-6 other files that have been previously marked as with minified but no longer are so. the bundleconfig.json file does not reflect those files are minifiable either. extremely weird and our team switched back to 2013 because of this.

**Comment by ssougnez** [comment]
Probably fixed by [this](https://github.com/madskristensen/BundlerMinifier/issues/123)

**Comment by madskristensen** [comment]
Yes, it has been fixed
