### ISSUE TITLE
MSBuild Target BuildDependsOn Order

### ISSUE THREAD

**Issue by JayQuerido** [madskristensen/BundlerMinifier#69]
In the .targets file, the `BuildDependsOn` node looks like this:

    <BuildDependsOn>
        $(BuildDependsOn);
        BundleMinify
    </BuildDependsOn>

We have a need to bundle and minify before compiling (our resources are embedded)... in other words, we need it to look like this:

    <BuildDependsOn>
        BundleMinify;
        $(BuildDependsOn)
    </BuildDependsOn>

Is there a way of structuring the targets file to allow this option for users of this package? Or some documentation on how we can use another custom target to manipulate MSBuild into doing this (without changing the package target, and keeping the ability to have NuGet manage it?

**Comment by madskristensen** [comment]
Yes, I did this for the Web Compiler extension, so I'll do that for this extension too now

**Comment by srollinet** [comment]
Then the problem is when you have typescript files and you rely on the typescript msbuild target, the ts files are compiled after the bundle is made

**Comment by brewdente** [comment]
@srollinet did you find a work around for this in the meantime?  I've been mucking with proj files and targets files, but it feels so dirty.

**Comment by srollinet** [comment]
@brewdente Finally we decided to add the bundled + minified file to the source control...
This solution is totally dirty, and the files conflict everytime but at least it works.

We tried to do something similar to your workaround, but we had some problems during the packaging, where the files where not bundled correctly

**Comment by bryandagnin** [comment]
We had problems with Clean and Rebuild using an approach similar to @brewdente (BundlerMinifier was failing due to missing TypeScript output subdirectories).
I've gone with this approach, which seems to be working in all cases so far.
The advantage of doing it this way is that you don't need to modify BundleWebCompiler.targets or BuildBundlerMinifier.targets.

At the bottom of your proj file:
``` XML
<PropertyGroup>
  <!-- BuildBundlerMinifier adds itself to the start of the build, we must intervene to get it to play nice with TypeScript -->
  <OriginalBuildDependsOn>$(BuildDependsOn)</OriginalBuildDependsOn>
</PropertyGroup>
<Import Project="..\packages\BuildBundlerMinifier.1.8.144\build\BuildBundlerMinifier.targets" Condition="Exists('..\packages\BuildBundlerMinifier.1.8.144\build\BuildBundlerMinifier.targets')" />
<Import Project="..\packages\BuildWebCompiler.1.8.284\build\BuildWebCompiler.targets" Condition="Exists('..\packages\BuildWebCompiler.1.8.284\build\BuildWebCompiler.targets')" />
<PropertyGroup>
  <!-- Revert BuildBundlerMinifier build order changes and put it last -->
  <BuildDependsOn>$(OriginalBuildDependsOn);WebCompile;BundleMinify</BuildDependsOn>
</PropertyGroup>
<Target Name="GenerateBuildBundlerMinifierDirectories">
  <ItemGroup>
    <TypeScriptOut Include="$(TypeScriptOutDir)\%(TypeScriptCompile.Identity)"/>
  </ItemGroup>
  <MakeDir Directories="%(TypeScriptOut.RelativeDir)"/>
</Target>
<PropertyGroup>
  <!-- Bundler clean requires the TypeScript destination directories to exist -->
  <CleanDependsOn>GenerateBuildBundlerMinifierDirectories;$(CleanDependsOn)</CleanDependsOn>
</PropertyGroup>
```
