### ISSUE TITLE
Bundles autoadded to vs project

### ISSUE THREAD

**Issue by brunis** [madskristensen/BundlerMinifier#71]
Hi,

Please stop adding bundles to my project files. I'll decide what goes into my projects, thank you very much.

regards,
Dennis

**Comment by madskristensen** [comment]
Set **includeInProject** to false https://github.com/madskristensen/BundlerMinifier/wiki/bundleconfig.json#includeinproject

**Comment by brunis** [comment]
Will you update the docs to reflect that default is true, not false?  Or make sure it defaults to false, which is what i would prefer, since you have to set it on each bundle, thanks.
