### ISSUE TITLE
Why not allow scss to bundle?

### ISSUE THREAD

**Issue by DennisRoam** [madskristensen/BundlerMinifier#72]
I'm having a hard time setting up a Visual Studio 2015 project to use webJs/Angular/Etc. 
Your tool(s) are an easier way to start getting things put together but I'm wondering why not allow scss files to bundle as well?

What I want to do:
/app/components has folders for each component so:
/app/components/show/show.html
/app/components/show/show.scss
/app/components/show/show.js

Then I run the bundler with my variables.scss file which allows me to just have 1 file for variables and not have to have specific @import for each component. 

Then the file compiles into css and thats the only file I include. 

Theres already great generators and tools for web apps but I'm making a universal windows app so none if it works...

any insight or if you could allow scss to bundle as well I'd appreciate it..

**Comment by madskristensen** [comment]
Because you would do that using scss syntax instead. Create a new file called all.scss and put import statements into it like so:

```css
@import "variables.scss";
@import "show.scss";
@import "another_component.scss";
```

That way you use SCSS itself to bundle. That's how I do it

**Comment by DennisRoam** [comment]
Well the issue is I have a lot of components or divided scss files and I could add @import to all of them to a base file but if I could merge them before compiling they stay very simple and easy to move around/change.

What I think I'll do is just do it with Gulp as part of the compiling pipeline which I've got figured out, just for newbies like me tools like yours are easier to setup/understand...
