### ISSUE TITLE
Minify JS : ASCII characters

### ISSUE THREAD

**Issue by Kain-Nosgoth** [madskristensen/BundlerMinifier#74]
Hello,

I use your extension to minify JS but I discovered a bug.

I use a table to convert characters with accents in normal character (é => e).

By against, the extension transforms the ASCII code in normal character. This is my bug JS

Digging through the code of the extension, I discovered that it possible to ignore  ASCII characters.

In the JavaScriptOptions class, the object  "CodeSettings" has the property "AlwaysEscapeNonAscii" that achieves the right result after minification.

For my own use, i re-compile your extension with this modification. Would it be possible to add an option in the json file to use this properties.

Thank you,
Rémi

No Minimy :
var defaultDiacriticsRemovalap =
[
	{ 'base': 'A', 'letters': '\u0041\u24B6\uFF21\u00C0\u00C1\u00C2\u1EA6\u1EA4\u1EAA\u1EA8\u00C3\u0100\u0102\u1EB0\u1EAE\u1EB4\u1EB2\u0226\u01E0\u00C4\u01DE\u1EA2\u00C5\u01FA\u01CD\u0200\u0202\u1EA0\u1EAC\u1EB6\u1E00\u0104\u023A\u2C6F' },
	{ 'base': 'AA', 'letters': '\uA732' },
	{ 'base': 'e', 'letters': '\u0065\u24D4\uFF45\u00E8\u00E9\u00EA\u1EC1\u1EBF\u1EC5\u1EC3\u1EBD\u0113\u1E15\u1E17\u0115\u0117\u00EB\u1EBB\u011B\u0205\u0207\u1EB9\u1EC7\u0229\u1E1D\u0119\u1E19\u1E1B\u0247\u025B\u01DD' },
];

Good Result after modify Extension:
var defaultDiacriticsRemovalap=[{base:"A",letters:"A\u24b6\uff21\u00c0\u00c1\u00c2\u1ea6\u1ea4\u1eaa\u1ea8\u00c3\u0100\u0102\u1eb0\u1eae\u1eb4\u1eb2\u0226\u01e0\u00c4\u01de\u1ea2\u00c5\u01fa\u01cd\u0200\u0202\u1ea0\u1eac\u1eb6\u1e00\u0104\u023a\u2c6f"},{base:"AA",letters:"\ua732"},{base:"e",letters:"e\u24d4\uff45\u00e8\u00e9\u00ea\u1ec1\u1ebf\u1ec5\u1ec3\u1ebd\u0113\u1e15\u1e17\u0115\u0117\u00eb\u1ebb\u011b\u0205\u0207\u1eb9\u1ec7\u0229\u1e1d\u0119\u1e19\u1e1b\u0247\u025b\u01dd"} ];

Bundle & Minify Result :
defaultDiacriticsRemovalap=[{base:"A",letters:"AⒶＡÀÁÂẦẤẪẨÃĀĂẰẮẴẲȦǠÄǞẢÅǺǍȀȂẠẬẶḀĄȺⱯ"},{base:"AA",letters:"Ꜳ"},{base:"e",letters:"eⓔｅèéêềếễểẽēḕḗĕėëẻěȅȇẹệȩḝęḙḛɇɛǝ"}];

**Comment by madskristensen** [comment]
Is there a negative side effect from this? I'm thinking this should just always be enabled and no setting needed?

**Comment by Kain-Nosgoth** [comment]
Hello,

Indeed, I think that there will be no side effects but I'm not on. That is why I proposed an option.

In my version of the extension, I set property "AlwaysEscapeNonAscii" at True.

CodeSettings settings = new CodeSettings();
settings.AlwaysEscapeNonAscii = true;
