### ISSUE TITLE
Minifier missing round brackets

### ISSUE THREAD

**Issue by edison99917** [madskristensen/BundlerMinifier#75]
When I minified javascript that has ternary operator, it omits the brackets which result in error in my javascript.

My script before minified:
this.boxHeight = parseInt((boxHeight != "" && boxHeight != "auto" && boxHeight.indexOf("%") == -1) ? boxHeight.substring(0, boxHeight.indexOf("px")) : this.box.scrollHeight);

After minified:
this.boxHeight=parseInt(n!=""&&n!="auto"&&n.indexOf("%")==-1?n.substring(0,n.indexOf("px")):this.box.scrollHeight);

Error produced:
0x800a138f - JavaScript runtime error: Unable to get property 'indexOf' of undefined or null reference

I think the correct code should be:
this.boxHeight=parseInt((n!=""&&n!="auto"&&n.indexOf("%")==-1)?n.substring(0,n.indexOf("px")):this.box.scrollHeight);

I run a few test with the original unminified and it's okay. Please help me to investigate this problem. 

Thank you.

**Comment by madskristensen** [comment]
Please open this issue with the [AjaxMin](http://ajaxmin.codeplex.com) component
