### ISSUE TITLE
Error when minifying CSS with @keyframes

### ISSUE THREAD

**Issue by Antfire70007** [madskristensen/BundlerMinifier#76]
I'm using the default bundling and minification in MVC 4.

One of our stylesheets starts with this bit of CSS:

@media (max-width: 979px) {
    @keyframes sidebarSlideInRight {
        from { right: -220px }

        to { right: 0 }
    }

    @-webkit-keyframes sidebarSlideInRight {
        from { right: -220px }

        to { right: 0 }
    }
}
The minification fails with this error: run-time error CSS1019: Unexpected token, found '}' and it points to the first character on line 13 (that's the very last } in the snippet above).

I'm not overly familiar with CSS in general and I was wondering:

Is that valid CSS? It fails validation at https://jigsaw.w3.org/css-validator/validator
What changes are needed to get the file minified? There are about 300 lines in the file so I would really like to get it minified if possible.

**Comment by madskristensen** [comment]
I don't know what the issue is with that particular CSS. Please raise the issue on the [AjaxMin](http://ajaxmin.codeplex.com/) issue tracker. That's the minification component this extension uses
