### ISSUE TITLE
Minify File insert duplicate entry in bundleconfig.json

### ISSUE THREAD

**Issue by Gambero81** [madskristensen/BundlerMinifier#77]
Suppose to have this file:
File.js

after minify action the result is:
File.js
  |-- File.min.js
and an entry of File.js is added in bundleconfig.json

now if i remove File.min.js from solution and reapply minify action on File.js another entry is added in bundleconfig.json

it would be correct do not add duplicate entry in bundleconfig.json if already present.
Thanks

**Comment by madskristensen** [comment]
Fixed
