### ISSUE TITLE
New config option to specify minified file name

### ISSUE THREAD

**Issue by ptashka-berkut** [madskristensen/BundlerMinifier#81]
It would be nice to have an option for specifying minitier output file name.

Could look something like this:
```json
{
    "inputFiles": [ "html/default.html" ],
    "outputFileName": "build/default.generated.html",
    "minify": { "enabled": true, "outputFileName": "build/default.html" }
}
```
Currenlty for the config above the minifier would create "build/default.generated.min.html" by default. From looking at the code I can see that the ".min" portion of the name is hard-coded in GetMinFileName().

This is mostly relevant for html files - e.g. we are curretly converting an old app to Typescript and are using BundlerMinifier for generating minified output js/css files. With HTML files the goal is on one hand to minify them, and on the other hand to not break the old URL for backwards compatibility. There is currenlty no control over the file name the minifier creates.

Thank you.

**Comment by madskristensen** [comment]
This is too specialized for me to implement. I don't think this would be helpful to a larger number of users
