### ISSUE TITLE
Nested bundles not allowed?

### ISSUE THREAD

**Issue by bitflower** [madskristensen/BundlerMinifier#83]
Hi,

in an Angular app I prefer to have all directives, services etc in ther own folder.
I've made 2 bundles - one for each folder.

In the top folder I've made a bundle containing these two generated files. 

THe problem/question: When I change a source file at the bottom the direct parent is updated - not the grandparent though.

Bug or feature or wrong application of the bundling mechanism?

Illustration:
myFramework [FOLDER]
-directives [SUBFOLDER]
--directive1.js
--directive2.js
--directives.js [BUNDLE]
-services [SUBFOLDER]
--service1.js
--service2.js
--services.js [BUNDLE]
-myFramework.js [BUNDLE]

Thanks!

**Comment by madskristensen** [comment]
This is not supported until we convert this extension to use the VS file system watcher service

**Comment by bitflower** [comment]
K, thanks for the rapid response. The new bundling is amazing anyway, thanks!
