### ISSUE TITLE
Some help please configuration for debugging vs publishing

### ISSUE THREAD

**Issue by mredman** [madskristensen/BundlerMinifier#87]
Hi,

I have just updated to Visual Studio 2015, and lucky enough have never used any bundling or minification in web application projects...until now that is..

This extension looks to be a lot simpler in usage and setup, however I need some help. I can see the actions to bundle and minify css or javascript files, which creates a .min.ext version of those files.

Now that we have the min.ext versions, do we just change our code to point to those instead?
This is ok and seems straight forward, however it would be great to not have things bundled and minified when debugging, to enable stepping through code etc? what happens when debugging, can we switch between bunded/minified and non bundled/minified?

**Comment by madskristensen** [comment]
For CSS I would always reference the .min.css file from the `<link>` element. For JavaScript, you could do a conditional thing in Razor or WebForms so you only reference the .min.js file in release mode. Something like `if (!HttpContext.Current.IsDebug) {...}`. I forgot what the actual property is called

**Comment by mredman** [comment]
ok great, simple is good.

**Comment by mredman** [comment]
Hi,

To solve my issue and make life easiet, I have created an htmlHelper (very quick solution) to help with this.

Code is here: https://bundlerminifierhelper.codeplex.com/

Example Usage (using relative paths, including the forward slash (/) :
@Html.Bundle("/Content/Styles/Site.min.css")
@Html.Bundle("/Scripts/Scripts.min.js")

When debugging all the input files will be rendered out to the page, and when not debugging, the supplied path will be rendered.

Hope this helps

**Comment by the-wazz** [comment]
I know this is old, but **please** add your response to the main docs (https://marketplace.visualstudio.com/items?itemName=MadsKristensen.BundlerMinifier). I've been looking for a good solution for over a day and this is the best and simplest way, and it's very hard to find.

Example:
`        <link href="<%= HttpContext.Current.IsDebuggingEnabled ? "/css/myFile.css" : TPRLibrary.Common.TPRFingerprint.Tag("/css/myFile.min.css") %>" rel="stylesheet" />
`
