### ISSUE TITLE
Saving edit to js file causes the bundle to update but does not minify

### ISSUE THREAD

**Issue by richardy706** [madskristensen/BundlerMinifier#91]
I am migrating a project from VS2013 to VS2015.  I have installed Web Essentials 2015.1 and the BundlerMinifier.  I was able to create the js bundle.  When I edit a file in the bundle and save the VS status bar indicates the bundle was updated and in fact the bundle.js file is updated but not the bundle.min.js.  If I go to the Task Runner Explorer, right click and click Run, the Task appears to run.  The Task Runner Explorer shows the word "Minified" in green and "Process terminated with code 0.  However the bundle.min.js file is not changed.  If I delete the bundle.min.js file and run the TASK, then the bundle.min.js file is created.  I see no errors in the Error List or Outut window.  If I select the "Re-minify all bundles in solution" option from the top level build menu, I see nothing at all happening.

What am I missing?

**Comment by 304NotModified** [comment]
So it's initial created but not updated?

**Comment by richardy706** [comment]
Yes.  The minified version is initially created but not updated when the bundle is updated.  I should note that I am determining this by looking at the last modified date of the file.

**Comment by richardy706** [comment]
I think I see what is happening.  Evidently i did not understand the minify process.  If a change to the source file does not result in a change to the min version, then the last modified date for the minified file does not change.  In our case some devs wrote js files that injected jQuery using a funciton wrapper like this:
```javascript
(function ($) {
    function test() {
        var temp = 12;
        console.log(temp);
        temp = test1(temp);
    }
    function test1(temp) {
        return temp++;
    }
})(jQuery);
```
This gets minified to:

(function(){})(jQuery);

I am not sure if this is correct or not but my issue was becasue I was making changes to the source inside the function wrapper which (since it is empty when minified) did not change the minified version.  If I change the above source to:
```javascript
//(function ($) {
    function test() {
        var temp = 14;
        console.log(temp);
        temp = test1(temp);
    }
    function test1(temp) {
        return temp++;
    }
//})(jQuery);
```
Then it is minifed to:

function test(){var n=14;console.log(n);n=test1(n)}function test1(n){return n++}

Any changes to the source file are now included in the bundle AND minified.

**Comment by madskristensen** [comment]
@richardy706 This looks correct to me. The reason it strips the `$` is because it isn't being used inside the closure

**Comment by madskristensen** [comment]
Also, the issue with not updating the output files have been fixed in the latest version
