### ISSUE TITLE
Fails to create minified file, complaining about valid regex

### ISSUE THREAD

**Issue by jasoncouture** [madskristensen/BundlerMinifier#92]
> C:\Users\plagu\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\uur5hdtt.fim\BundlerMinifier.exe "C:\Users\plagu\Source\Repos\NightOwl-Jason\NightOwl\NightOwlWeb\bundleconfig.json"
  Minified
Syntax error in regular expression: /(^|\s|>|\b)_(?=\S)([^]+?)_(?=\b|<|\s|$)/gm
Syntax error in regular expression: /(^|\s|>|\b)__(?=\S)([^]+?)__(?=\b|<|\s|$)/gm
Process terminated with code 0.

Problem javascript source file:
[showdown.txt](https://github.com/madskristensen/BundlerMinifier/files/69856/showdown.txt)

I believe the issue is [^], while valid, is strange.

**Comment by madskristensen** [comment]
Please report this issue to the AjaxMin project here http://ajaxmin.codeplex.com/

**Comment by cunnpole** [comment]
ajaxmin appears to be dead for about 2 years so I guess we'll never get a fix for this
